new package: libandroid-execinfo
termux/termux-packages pull request #10375
Opened 2022-04-28 06:46 UTC by licy183

Closes #10365

2022-04-28 07:47 UTC, Grimler91 reviewed
Maybe add a comment in the build.sh about which repo the files are taken from, to make it easier to check for updates upstream in the future

2022-04-28 09:05 UTC, buttaface commented
Also, put something in the description so that users can figure out which libexecinfo package to use, feel free to change the other one's description too.

2022-05-03 22:38 UTC, xtkoba requested changes
Otherwise (than `memfd_create`) I see that the changes made to the original code are a matter of porting from C++ to C and nothing is strange. Thanks!

2022-05-03 22:38 UTC, xtkoba commented on packages/libandroid-execinfo/execinfo.c
> +}
Try `memfd_create` syscall first. Define `memfd_create` as follows:

```c
#include <sys/syscall.h>

/* ... */

#if defined __ANDROID__ && __ANDROID_API__ < 30
#define memfd_create(name,flags) syscall(SYS_memfd_create,name,flags)
#endif
```

Fall back to `mkstemp` only when it failed (returned `-1`).

2022-05-04 06:04 UTC, xtkoba approved these changes

2022-05-04 06:05 UTC, merged

2022-05-04 06:15 UTC, buttaface commented
We now have two packages that install a `libexecinfo.so`, one that describes itself as `A quick-n-dirty BSD licensed clone of backtrace facility found in the GNU libc` and this one as `Shared library for the backtrace system function`, so nobody will know which one to use. This is a mess.

2022-05-04 06:36 UTC, licy183 commented
> We now have two packages that install a `libexecinfo.so`, one that describes itself as `A quick-n-dirty BSD licensed clone of backtrace facility found in the GNU libc` and this one as `Shared library for the backtrace system function`, so nobody will know which one to use. This is a mess.

Yeah, it seems a bad thing. In my opinion, `libexecinfo` provides a much faster `backtrace` functionality than the bionic libc's port because it doens't use the file io, but it only works on arm arch. I failed to execute the binary linked against it under a x86_64 Android emulator.