ani-cli dependency bugfix
termux/termux-packages pull request #10485
Opened 2022-05-04 08:38 UTC by port19x

I intentionally separated this into 3 commits:

- throughout the lifetime of this package we never depended on git
- we prefer termux-tools over listing curl, grep, sed individually since we may expand our use of other coreutils. If this conflicts with policy, this can easily be reverted
- At least in my personal testing, ani-cli cannot find openssl if you just install openssl. We interact with the openssl commandline programm, so openssl-tool is required

Draft PR because we'll probably release 2.2 soon

Greetings from upstream

2022-05-04 08:43 UTC, port19x commented
Testing on GrapheneOS, latest Termux from Fdroid.
ani-cli v2.1 is broken due to some stuff that happened early april, as said previously a release is just around the corner

2022-05-04 08:44 UTC, port19x commented
How have you set up the automatic review request / code owners?

2022-05-04 09:14 UTC, Grimler91 requested changes
Greetings!

Please prefix the commits with `ani-cli:` so that it's easy to see which package is changed when looking through git history (see [format of previous commits](https://github.com/termux/termux-packages/commits/master)).

Replacing sed, curl and grep dependencies with termux-tools happens to work since termux-tools depend on all of those, but that could change in the future. I think explicitly listing the dependencies makes more sense, makes it easier to see which packages that might break on for example a curl update. For future updates we'll just have to keep an eye on the [README](https://github.com/pystardust/ani-cli#Dependencies) to see if any additional coreutils have been added as dependencies.

2022-05-05 20:46 UTC, port19x commented
Version 2.2 out now
https://github.com/pystardust/ani-cli/releases/tag/v2.2

2022-05-05 20:54 UTC, port19x commented
Should have double checked before commiting...
You guys don't have awk packaged?

2022-05-06 04:16 UTC, Grimler91 commented
We package GNU's awk under the name [gawk](https://github.com/termux/termux-packages/tree/master/packages/gawk)

2022-05-06 05:46 UTC, Grimler91 commented
Please rebase the PR as well to get rid of the merge commit

2022-05-06 10:04 UTC, port19x commented
fetching upstream and rebaseing don't seem to go well together...

2022-05-06 11:36 UTC, merged

2022-05-06 11:37 UTC, Grimler91 commented
Thanks!