parted: update to 3.5
termux/termux-packages pull request #10912
Opened 2022-06-07 00:20 UTC by tjhexf

2022-06-07 00:44 UTC, tjhexf commented
removed one of the patches. It doesn't seem to be necessary anymore? Or atleast that specific code piece that was patched does not seem to exist anywhere in the configure file anymore. 
Could be wrong, tho.

2022-06-11 17:47 UTC, MrAdityaAlok requested changes

2022-06-11 17:47 UTC, MrAdityaAlok commented on packages/parted/configure-pthreads-no-weak.patch
> -diff -uNr inetutils-1.9.4/configure inetutils-1.9.4.mod/configure
> removed one of the patches. It doesn't seem to be necessary anymore? Or atleast that specific code piece that was patched does not seem to exist anywhere in the configure file anymore. Could be wrong, tho.

Yes, it is wrong. Update with following patch:
```patch
--- ./configure.orig	2022-06-11 17:35:38.249779008 +0000
+++ ./configure	2022-06-11 17:37:22.492718680 +0000
@@ -17193,7 +17193,7 @@
           else
             if case "$gl_cv_have_weak" in *yes) true;; *) false;; esac; then
 
-printf "%s\n" "#define USE_POSIX_THREADS_WEAK 1" >>confdefs.h
+#printf "%s\n" "#define USE_POSIX_THREADS_WEAK 1" >>confdefs.h
 
               LIBTHREAD= LTLIBTHREAD=
             else
```

2022-06-11 17:50 UTC, MrAdityaAlok commented
Please, also change commit message to:
```
upgpkg(main/parted): update to 3.5
```
And rebase against master.

2022-06-11 18:00 UTC, tjhexf commented
will do. Thanks!

2022-06-11 18:13 UTC, MrAdityaAlok approved these changes

2022-06-11 18:16 UTC, merged