add(main): new package glab-cli
termux/termux-packages pull request #10947
Opened 2022-06-11 09:38 UTC by 2096779623

Close #10945.

2022-06-11 16:09 UTC, MrAdityaAlok commented
Make sure that you add `TERMUX_PKG_EXTRA_MAKE_ARGS="GLAB_VERSION=${TERMUX_PKG_VERSION}"`.

2022-06-12 01:40 UTC, 2096779623 commented
> Make sure that you add `TERMUX_PKG_EXTRA_MAKE_ARGS="GLAB_VERSION=${TERMUX_PKG_VERSION}"`.

Added,thanks!

2022-06-12 04:27 UTC, MrAdityaAlok requested changes

2022-06-12 04:27 UTC, MrAdityaAlok commented on packages/glab-cli/build.sh
> +termux_step_make() {
Please remove this. Since it has Makefile, it will be automatically called.

2022-06-12 04:27 UTC, MrAdityaAlok commented on packages/glab-cli/build.sh
> +	      termux_setup_golang
Indent with single tab or alternatively it's better to install [shfmt](https://github.com/mvdan/sh) formatter to do it for you.

You may install it using:
```
go install mvdan.cc/sh/v3/cmd/shfmt@latest
```

2022-06-12 04:27 UTC, MrAdityaAlok commented on packages/glab-cli/build.sh
> +	      go mod init || :
Remove line 15-16 also. They shouldn't be needed.

2022-06-12 05:14 UTC, merged