sdl2-mixer: Enable MOD support
termux/termux-packages pull request #11234
Opened 2022-07-13 12:47 UTC by ar664

2022-07-13 13:11 UTC, 2096779623 requested changes
* Please modify the URL in `TERMUX_PKG_HOMEPAGE` to `https://github.com/libsdl-org/SDL_mixer`.
* Update to `2.6.1`.
* After doing the above two things, please squash the commits.

2022-07-13 17:12 UTC, ar664 commented
@2096779623 Should be good now.

2022-07-13 23:13 UTC, 2096779623 approved these changes

2022-07-14 06:00 UTC, merged

2022-07-14 06:48 UTC, Ramin1333 commented
ل


در تاریخ پنجشنبه ۱۴ ژوئیهٔ ۲۰۲۲،‏ ۱۰:۳۲ 2096779623 ***@***.***>
نوشت:

> Merged #11234 <https://github.com/termux/termux-packages/pull/11234> into
> master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/termux/termux-packages/pull/11234#event-6991329982>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXD3U22OGUW3AGY6UVYA3YTVT6UPBANCNFSM53OTNOGQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-07-14 06:49 UTC, Ramin1333 commented
تو هکری

در تاریخ پنجشنبه ۱۴ ژوئیهٔ ۲۰۲۲،‏ ۱۱:۱۸ Radical ***@***.***>
نوشت:

> ل
>
>
> در تاریخ پنجشنبه ۱۴ ژوئیهٔ ۲۰۲۲،‏ ۱۰:۳۲ 2096779623 <
> ***@***.***> نوشت:
>
>> Merged #11234 <https://github.com/termux/termux-packages/pull/11234>
>> into master.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/termux/termux-packages/pull/11234#event-6991329982>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AXD3U22OGUW3AGY6UVYA3YTVT6UPBANCNFSM53OTNOGQ>
>> .
>> You are receiving this because you are subscribed to this thread.Message
>> ID: ***@***.***>
>>
>