enhance(main/termux-tools): new motd design
termux/termux-packages pull request #11250
Opened 2022-07-14 18:34 UTC by TermuxMonet

For aesthetic pruposes, changed the motd by adding a small termux icon, termux version display and a hint to fix repo issues related to termux-change repo. 
And also, now login executes a dynamic motd.sh, which can expand environment variables and display text formatting.
Common motd support wasn't removed, since now the login just distinguishes between dynamic and common motd (prioritising the dynamic motd)

Preview: 
![Screenshot_20220710-214038_Termux~01](https://user-images.githubusercontent.com/103902727/178170466-460ed8df-4969-4b50-a588-49501f9402f2.png)

(Duplicate of #11222. Previous commit got broken)

Co-authored-by: [TomJo2000](https://github.com/TomJo2000/)

2022-07-14 20:30 UTC, Maxython requested changes
I think that the information about fixing the termux repository will not be relevant for pacman users. Add this message only for the debian package.

2022-07-14 20:43 UTC, DevMoxxie commented
> I think that the information about fixing the termux repository will not be relevant for pacman users. Add this message only for the debian package.

Done

2022-07-14 20:57 UTC, Maxython approved these changes

2022-07-15 03:05 UTC, 2096779623 approved these changes

2022-07-19 14:14 UTC, DevMoxxie commented
Is this PR gonna be merged?

2022-07-19 14:17 UTC, 2096779623 commented
> Is this PR gonna be merged?

LGTM, of course.

Wait for the github action to finish before merging it.

2022-07-19 14:30 UTC, merged

2022-07-20 06:36 UTC, wmcbtech30 commented
I think its better the previous motd design should be used or without the Termux logo. zooming in/out the terminal would mess the logo up and makes the motd unreadable in portrait screens
![Screenshot_2022-07-20-14-35-07-33_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/65075766/179913368-95f4d2c6-23f1-472b-bb0c-79b3044fd72d.jpg)

2022-07-20 06:41 UTC, agnostic-apollo commented
This was mentioned to OP but wasn't removed. Text word wrap is fine, icon wrapping is not good and can't be avoided. Other changes are fine, didn't get time to test.

https://github.com/termux/termux-packages/pull/11222#issuecomment-1179903683

2022-07-20 07:18 UTC, truboxl commented
Merged too early I guess...

2022-07-20 13:20 UTC, DevMoxxie commented
> I think its better the previous motd design should be used or without the Termux logo. zooming in/out the terminal would mess the logo up and makes the motd unreadable in portrait screens

Too late for a hotfix? this can be fixed by adding a character (dot) inside the logo squares
and then, the terminal shouldn't delete any empty lines (and the logo isn't destroyed)
![Screenshot_20220720-101628_Termux](https://user-images.githubusercontent.com/103902727/179992307-cdfea52b-6e1a-46ea-8b5a-3b959741d4ba.png)

2022-08-03 11:34 UTC, gascs commented
I don't think the existence of this micro logo is necessary, after I updated my terminal, he messed up my original layout, and I couldn't modify it at first, and the logo is very unaesthetic, yes it's very lacking  aesthetics!

2022-08-03 11:36 UTC, gascs commented
And this move is superfluous, which makes my original modification method invalid, and I am very distressed

2022-08-03 11:53 UTC, agnostic-apollo commented
The icon only is planned to be removed from new motd due to word wrap issue, rest will stay, didn't get time to fix. Can provide an env variable for users to have their own as well, so that whoever likes icons and stuff can use one easily without requiring modifications on package updates.

2022-08-03 11:56 UTC, TomJo2000 commented
> The icon only is planned to be removed from new motd due to word wrap issue, rest will stay, didn't get time to fix. Can provide an env variable for users to have their own as well, so that whoever likes icons and stuff can use one easily without requiring modifications on package updates.

btw I think I've worked out a solution to the line wrapping issue, I just haven't had the time to fully test it yet.

2022-08-03 11:59 UTC, agnostic-apollo commented
I see, how are you doing it?

2022-08-03 12:02 UTC, gascs commented
什么？

2022-08-03 12:03 UTC, gascs commented
> I see, how are you doing it?

what?

2022-08-03 12:12 UTC, TomJo2000 commented
> I see, how are you doing it?

By checking the `$COLUMNS` environment variable against the width of the logo

2022-08-03 12:13 UTC, TomJo2000 commented
That itself wouldn't prevent wrapping from zooming in though.

2022-08-03 12:13 UTC, agnostic-apollo commented
>By checking the $COLUMNS environment variable against the width of the logo

Resizing after motd has already been generated will still break it and make it "unreadable".

2022-08-03 12:14 UTC, TomJo2000 commented
> Resizing after motd has already been generated will still break it and make it "unreadable".

That's what I'm still working on.

2022-08-03 12:16 UTC, agnostic-apollo commented
The env variable for custom motd file is a better option for you guys. The defaults should not break. Maybe an additional env variable that decides whether icon should be printed or not could be added too, then custom motd file will not need to be downloaded/created by users.

2022-08-03 12:18 UTC, TomJo2000 commented
> The env variable for custom motd file is a better option for you guys. The defaults should not break. Maybe an additional env variable that decides whether icon should be printed or not could be added too, then custom motd file will not need to be downloaded/created by users.
That's also a good idea, I'll have to see when I have some time to work out the kinks on this.

2022-08-03 12:23 UTC, agnostic-apollo commented
Note that `termux-tools` is in the process of being moved to https://github.com/termux/termux-tools

2022-08-03 12:30 UTC, TomJo2000 commented
I'll wanna make sure it's all working as intended before making a Pull Request, so I'll keep it in mind for later.

2022-08-09 21:08 UTC, TomJo2000 commented
Update on this.
I've just pushed a first draft of a proper fix for the wrapping issue to my fork of termux-tools.
https://github.com/TomJo2000/motd-wrap/commit/2dd269a2f0b15cad1e5ff68b1bb6b1095205630f

Hopefully I'll have time to touch this up and make a Pull Request over on termux-tools tomorrow, although I just stopped a new internship and I've been incredibly busy.
I hope we can get this issue fixed as soon as possible though.