ytfzf: update to 2.4.0
termux/termux-packages pull request #11314
Opened 2022-07-21 19:50 UTC by Euro20179

2022-07-21 20:14 UTC, Grimler91 requested changes

2022-07-21 20:14 UTC, Grimler91 commented on packages/ytfzf/build.sh
> +TERMUX_PKG_VERSION=1:2.4.0
Prepended `1:` can be removed, doesn't seem to do do anything

2022-07-22 02:38 UTC, 2096779623 requested changes
Can you squash the commits?

2022-07-22 03:31 UTC, licy183 requested changes

2022-07-22 03:31 UTC, licy183 commented on packages/ytfzf/ytfzf.patch
> ++	jobs_file="${TMPDIR:-@TERMUX_PREFIX@}/the-jobs-need-to-be-written-to-a-file.list"
`/tmp` should be replaced to `@TERMUX_PREFIX/tmp`.

2022-07-22 03:31 UTC, licy183 commented on packages/ytfzf/ytfzf.patch
> ++: "${YTFZF_SYSTEM_ADDON_DIR:=@TERMUX_PREFIX@/local/share/ytfzf/addons}"
`/usr/local/a` should be replaced with `@TERMUX_PRFIX/a`. I think `/local` is not necessary.

2022-07-22 03:31 UTC, licy183 commented on packages/ytfzf/ytfzf.patch
> ++	tmp_env=@TERMUX_PREFIX@/ytfzf-env
`/tmp` should be replaced to `@TERMUX_PREFIX/tmp`.

2022-07-22 05:22 UTC, 2096779623 approved these changes

2022-07-22 06:05 UTC, merged

2022-07-22 06:05 UTC, Grimler91 commented
Thanks!