Adding Hetzner Cloud CLI (hcloud command)
termux/termux-packages pull request #11375
Opened 2022-07-28 20:18 UTC by confund0

2022-07-28 21:19 UTC, Grimler91 requested changes
Thanks for the PR! Please see comment

2022-07-28 21:19 UTC, Grimler91 commented on packages/hcloud/build.sh
> +HCLOUD_PKG_VERSION="v${TERMUX_PKG_VERSION}"
Please drop this variable and just specify `v${TERMUX_PKG_VERSION}` in SRCURL and `LD_FLAGS`

2022-07-28 22:16 UTC, confund0 commented
Done. New PR 11376.

2022-07-29 02:08 UTC, 2096779623 commented
> Done. New PR 11376.

Don't create multiple PRs for the same request.
Can you squash the commit?

2022-07-29 11:46 UTC, closed without merging