new package: libmuparser
termux/termux-packages pull request #11424
Opened 2022-08-02 11:47 UTC by pvonmoradi

Adds [muparser](https://beltoforion.de/en/muparser/) library for parsing math expressions.

2022-08-02 12:45 UTC, Grimler91 requested changes

2022-08-02 12:45 UTC, Grimler91 commented on packages/libmuparser/build.sh
> +library written in C++"
Why line break? Will break something or at least look weird on device

2022-08-02 12:45 UTC, Grimler91 commented on packages/libmuparser/build.sh
> +TERMUX_PKG_LICENSE_FILE="LICENSE"
This line shouldn't be needed, LICENSE is one of the filenames [termux_step_install_license looks for](https://github.com/termux/termux-packages/blob/master/scripts/build/termux_step_install_license.sh#L35-L38)

2022-08-02 12:45 UTC, Grimler91 commented on packages/libmuparser/build.sh
> +TERMUX_PKG_BUILD_DEPENDS="cmake"
This line is not needed, cmake is installed by build system automatically. `TERMUX_PKG_BUILD_DEPENDS` means that it downloads cmake that has been cross-compiled for termux, and that cmake cannot be used in any case

2022-08-05 00:04 UTC, truboxl commented
Please add `TERMUX_PKG_DEPENDS="libc++"`

2022-08-06 03:51 UTC, merged