new package: libmatio
termux/termux-packages pull request #11426
Opened 2022-08-02 12:39 UTC by pvonmoradi

Adds [libmatio](https://github.com/tbeu/matio) for reading and writing binary MATLAB MAT files.

2022-08-02 12:42 UTC, Grimler91 requested changes
Thanks! Two things to improve

2022-08-02 12:42 UTC, Grimler91 commented on packages/libmatio/build.sh
> +TERMUX_PKG_BUILD_DEPENDS="cmake"
This line is not needed, cmake is installed by build system automatically. `TERMUX_PKG_BUILD_DEPENDS` means that it downloads cmake that has been cross-compiled for termux, and that cmake cannot be used in any case

2022-08-02 12:42 UTC, Grimler91 commented on packages/libmatio/build.sh
> +TERMUX_PKG_LICENSE_FILE="COPYING"
This line shouldn't be needed, COPYING is one of the filenames [termux_step_install_license looks for](https://github.com/termux/termux-packages/blob/master/scripts/build/termux_step_install_license.sh#L35-L42)

2022-08-02 13:35 UTC, pvonmoradi commented
@Grimler91  Why is this building ok in my ubuntu 20.04 instance? 
[log.txt](https://github.com/termux/termux-packages/files/9242632/log.txt)

2022-08-02 14:05 UTC, Grimler91 commented
Github actions does a "fast build" where it downloads dependencies (`./build-package -i libmatio`) instead of building them, seems downloading pre-built libhdf5 vs building it gives different result.

Seems libmatio looks for static libhdf5 instead of shared library. Probably we want to change so that it used shared library instead with a configure arg or patch, to save disk space for users

2022-08-03 13:53 UTC, pvonmoradi commented
@Grimler91 I disabled libhdf5 (and hence support for v7.3 MAT files) with these switches. The build system ignores my directive of using the shared hdf5 libs (.so files) and looks for static (.a) files. 
```cmake
-DMATIO_WITH_HDF5:BOOL=OFF
-DMATIO_MAT73:BOOL=OFF
-DHDF5_USE_STATIC_LIBRARIES:BOOL=OFF
-DMATIO_SHARED:BOOL=ON
```

Here is the set of switches that _should have_ worked but don't:
```cmake
-DMATIO_WITH_HDF5:BOOL=ON
-DMATIO_MAT73:BOOL=ON
-DHDF5_USE_STATIC_LIBRARIES:BOOL=OFF
-DMATIO_SHARED:BOOL=ON
```

2022-09-04 15:27 UTC, Grimler91 reviewed
One last cosmetic change, then I'll merge it!

2022-09-04 15:27 UTC, Grimler91 commented on packages/libmatio/build.sh
> +TERMUX_PKG_EXTRA_CONFIGURE_ARGS='
Please change to " here, no need for single quotes

2022-09-06 18:27 UTC, merged