New package: Code::blocks
termux/termux-packages pull request #11529
Opened 2022-08-10 11:59 UTC by ifurther

2022-08-10 12:05 UTC, Grimler91 commented on x11-packages/codeblocks/build.sh
> + Environment (IDE)."
Please write description on a single line

2022-08-10 12:06 UTC, Grimler91 requested changes
Please squash the commits and rebase to get rid of the merge commits

2022-08-10 12:15 UTC, Grimler91 requested changes
Please use tabs for indentation, as outlined in the [coding guidelines](https://github.com/termux/termux-packages/wiki/Coding-guideline)

2022-08-10 12:16 UTC, ifurther commented on x11-packages/codeblocks/build.sh
> + Environment (IDE)."
Sorry, I fixed.

2022-11-01 20:40 UTC, Grimler91 requested changes
Please rebase to get rid of the merge commits, and re-write the commit messages `add patch file for wxWidgets3.16` and `disable compiler` so that it is easier to se what package they affect, for example by prefixing `codeblocks:`

2023-01-09 22:00 UTC, xtkoba commented
Cleanup will be done in #14429.

2023-01-09 22:00 UTC, closed without merging