mpd: add pulseaudio output to the default config
termux/termux-packages pull request #11703
Opened 2022-08-24 04:14 UTC by alive4ever

Since mpd depends on pulseaudio, add the possibility to use pulseaudio
output. Disabled by default.

2022-08-24 04:16 UTC, 2096779623 requested changes
Please bump REVISION .

2022-08-24 04:29 UTC, alive4ever commented
> Please bump REVISION .

Done.

2022-08-24 05:09 UTC, tomty89 commented
https://github.com/MusicPlayerDaemon/MPD/blob/v0.23.9/doc/mpdconf.example#L290

2022-08-27 08:38 UTC, tomty89 commented
I don't understand. What's the point of this PR / uncommenting the lines and add enabled no?

2022-08-28 09:31 UTC, alive4ever commented
> I don't understand. What's the point of this PR / uncommenting the lines and add enabled no?

Let's take a look at the currently shipped default mpd configuration.

```bash
$ sed '/^#/d;/^$/d' < $PREFIX/etc/mpd.conf
```

```
music_directory		"/sdcard/Music"
playlist_directory		"~/.mpd/playlists"
db_file			"~/.mpd/database"
log_file			"~/.mpd/log"
pid_file			"~/.mpd/pid"
state_file			"~/.mpd/state"
sticker_file			"~/.mpd/sticker.sql"
bind_to_address		"/data/data/com.termux/files/usr/var/run/mpd.socket"
follow_outside_symlinks	"yes"
follow_inside_symlinks		"yes"
input {
        plugin "curl"
}
audio_output {
        type            "sles"
        name            "OpenSLES output"
        mixer_type      "software"
}
audio_output {
	type		"openal"
	name		"OpenAL output"
	mixer_type	"software"
	device		"OpenSL"
	enabled		"no"
}
audio_output {
        type            "fifo"
        name            "ncmpcpp visualizer"
        path            "/data/data/com.termux/files/usr/var/run/mpd.fifo"
        format          "44100:16:2"
	enabled		"no"
}

```
There are three outputs: sles, openal, and fifo.

The three outputs listed on the default configuration can be easily enabled, i.e. by opening `ncmpcpp` and pressing `7` to go to `Outputs` window. The output shown on the `ncmpcpp` can be toggled by pressing `Enter`.

![Screenshot_20220828-162916](https://user-images.githubusercontent.com/7654911/187067339-5e4bce42-cf81-4370-b091-c49942526379.png)

This pull-request proposes the addition of `pulse` output to be listed on the `outputs` sections of `ncmpcpp` or other mpd clients, so users can enable `pulse` output without the hassle of editing `$PREFIX/etc/mpd.conf` just like the way `openal` output is listed on the default configuration.

2022-10-01 16:05 UTC, Grimler91 reviewed
I would suggest to keep the optional options:

```
#	server		"remote_server"		# optional
#	sink		"remote_server_sink"	# optional
#	media_role	"media_role"		# optional
```

so that users get a hint how remotes can be configured. Apart from that it looks acceptable to me

2023-01-26 14:13 UTC, merged