add(main): new package opencolorio
termux/termux-packages pull request #11712
Opened 2022-08-24 14:00 UTC by T-Dynamos

#11674

2022-08-25 12:53 UTC, T-Dynamos commented
```
[413/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/builtins/Displays.cpp.o
[414/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/builtins/RedCameras.cpp.o
[415/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/DisplayViewTransform.cpp.o
[416/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/BuiltinTransform.cpp.o
[417/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/ColorSpaceTransform.cpp.o
[418/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/CDLTransform.cpp.o
[419/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/ExponentTransform.cpp.o
[420/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/ExponentWithLinearTransform.cpp.o
[421/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/ExposureContrastTransform.cpp.o
[422/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/FixedFunctionTransform.cpp.o
[423/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/GradingPrimaryTransform.cpp.o
[424/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/GradingRGBCurveTransform.cpp.o
[425/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/FileTransform.cpp.o
[426/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/GradingToneTransform.cpp.o
[427/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/LogAffineTransform.cpp.o
[428/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/GroupTransform.cpp.o
[429/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/LogCameraTransform.cpp.o
[430/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/LogTransform.cpp.o
[431/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/LookTransform.cpp.o
[432/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/Lut1DTransform.cpp.o
[433/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/Lut3DTransform.cpp.o
[434/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/MatrixTransform.cpp.o
[435/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/transforms/RangeTransform.cpp.o
[436/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/ViewTransform.cpp.o
[437/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/ViewingRules.cpp.o
[438/448] Building CXX object src/OpenColorIO/CMakeFiles/OpenColorIO.dir/SystemMonitor.cpp.o
[439/448] Linking CXX shared library src/OpenColorIO/libOpenColorIO.so
FAILED: src/OpenColorIO/libOpenColorIO.so 
: && /home/builder/.termux-build/_cache/android-r25-api-24-v1/bin/clang++ --target=aarch64-none-linux-android --gcc-toolchain=/home/builder/.termux-build/_cache/android-r25-api-24-v1 --sysroot=/home/builder/.termux-build/_cache/android-r25-api-24-v1/sysroot -fPIC -fstack-protector-strong -Oz --target=aarch64-linux-android24  -I/data/data/com.termux/files/usr/include -O3 -DNDEBUG  -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now --target=aarch64-linux-android24  -Wl,--exclude-libs,ALL -shared -Wl,-soname,libOpenColorIO.so -o src/OpenColorIO/libOpenColorIO.so src/OpenColorIO/CMakeFiles/OpenColorIO.dir/apphelpers/CategoryHelpers.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/apphelpers/ColorSpaceHelpers.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/apphelpers/DisplayViewHelpers.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/apphelpers/LegacyViewingPipeline.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/apphelpers/MixingHelpers.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/Baker.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/BitDepthUtils.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/Caching.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/ColorSpace.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/ColorSpaceSet.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/Config.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/Context.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/ContextVariableUtils.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/CPUProcessor.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/Display.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/DynamicProperty.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/Exception.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/cdl/CDLParser.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/cdl/CDLReaderHelper.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/cdl/CDLWriter.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/ctf/CTFReaderHelper.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/ctf/CTFReaderUtils.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/ctf/CTFTransform.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/ctf/IndexMapping.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormat3DL.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatCCC.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatCC.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatCDL.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatCSP.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatCTF.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatDiscreet1DL.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatHDL.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatICC.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatIridasCube.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatIridasItx.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatIridasLook.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatPandora.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatResolveCube.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatSpi1D.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatSpi3D.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatSpiMtx.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatTruelight.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatUtils.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FileFormatVF.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/FormatMetadata.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/xmlutils/XMLReaderHelper.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/xmlutils/XMLReaderUtils.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/fileformats/xmlutils/XMLWriterUtils.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/FileRules.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/GPUProcessor.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/GpuShader.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/GpuShaderDesc.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/GpuShaderClassWrapper.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/GpuShaderUtils.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/HashUtils.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/ImageDesc.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/ImagePacking.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/Logging.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/Look.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/LookParse.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/MathUtils.cpp.o src/OpenColorIO/CMakeFiles/OpenColorIO.dir/md5/md5.cpp.o src/OpenColorIO/CMakeFiles/OpenC [...]

2022-08-30 13:24 UTC, Grimler91 commented
Seems this was closed since it was linked to libexpat fix PR

2022-08-30 15:27 UTC, T-Dynamos commented
```
 /home/builder/.termux-build/_cache/android-r25-api-24-v1/bin/clang++ --target=aarch64-none-linux-android --gcc-toolchain=/home/builder/.termux-build/_cache/android-r25-api-24-v1 --sysroot=/home/builder/.termux-build/_cache/android-r25-api-24-v1/sysroot -DOCIO_SOURCE_DIR=/home/builder/.termux-build/opencolorio/src -DOCIO_UNIT_TEST_FILES_DIR=/home/builder/.termux-build/opencolorio/build/testdata -DOpenColorIO_SKIP_IMPORTS -I/home/builder/.termux-build/opencolorio/src/tests/cpu -I/home/builder/.termux-build/opencolorio/src/include/OpenColorIO/.. -I/home/builder/.termux-build/opencolorio/src/include/OpenColorIO -I/home/builder/.termux-build/opencolorio/src/src/OpenColorIO -I/home/builder/.termux-build/opencolorio/build/include/OpenColorIO -I/home/builder/.termux-build/opencolorio/src/tests/testutils/.. -isystem /home/builder/.termux-build/opencolorio/build/src/utils/.. -isystem /data/data/com.termux/files/usr/include/Imath -isystem /data/data/com.termux/files/usr/lib -isystem /home/builder/.termux-build/opencolorio/src/ext/sampleicc/src/include -isystem /home/builder/.termux-build/opencolorio/src/src/utils/.. -fstack-protector-strong -Oz --target=aarch64-linux-android24  -I/data/data/com.termux/files/usr/include -O3 -DNDEBUG -fPIE -fvisibility=hidden -fvisibility-inlines-hidden  -DUSE_CLANG -Wno-deprecated-register -Wall -Wextra -Wswitch-enum -std=c++11 -MD -MT tests/cpu/CMakeFiles/test_cpu_exec.dir/__/__/src/OpenColorIO/OCIOYaml.cpp.o -MF tests/cpu/CMakeFiles/test_cpu_exec.dir/__/__/src/OpenColorIO/OCIOYaml.cpp.o.d -o tests/cpu/CMakeFiles/test_cpu_exec.dir/__/__/src/OpenColorIO/OCIOYaml.cpp.o -c /home/builder/.termux-build/opencolorio/src/src/OpenColorIO/OCIOYaml.cpp
/home/builder/.termux-build/opencolorio/src/src/OpenColorIO/OCIOYaml.cpp:22:10: fatal error: 'pystring/pystring.h' file not found
#include "pystring/pystring.h"
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
[30/440] Building CXX object tests/cpu/CMakeFiles/test_cpu_exec.dir/__/__/src/OpenColorIO/ops/cdl/CDLOpGPU.cpp.o
```
Why still not fixed by #11732

2022-08-30 16:49 UTC, Grimler91 commented
Probably `pystring.h` should have been installed to `$PREFIX/include/pystring/` instead of `$PREFIX/include/`, since it looks for `"pystring/pystring.h"`

2022-09-06 18:30 UTC, T-Dynamos commented
@Grimler91 Please open this pr

2022-09-07 01:07 UTC, T-Dynamos commented
```
-- Found PythonInterp: /usr/bin/python3.10 (found version "3.10.4") 
CMake Error at tools/FindPythonLibsNew.cmake:161 (message):
  Python config failure: Python is 64-bit, chosen compiler is 32-bit
Call Stack (most recent call first):
  tools/pybind11Tools.cmake:38 (find_package)
  tools/pybind11Common.cmake:201 (include)
  CMakeLists.txt:169 (include)


-- Configuring incomplete, errors occurred!
See also "/home/builder/.termux-build/opencolorio/build/ext/build/pybind11/src/pybind11_install-build/CMakeFiles/CMakeOutput.log".
[8/440] Building CXX object tests/utils/CMakeFiles/test_utils_exec.dir/StringUtils_tests.cpp.o
ninja: build stopped: subcommand failed.
```
How to fix it?

2022-09-07 10:20 UTC, ifurther commented
Please remove link libexpat.so.1.8.8, and it should binding Python?

2022-09-16 09:38 UTC, ifurther commented
Maybe close python binding to build, set `-DOCIO_BUILD_PYTHON=off`

2022-09-25 06:17 UTC, T-Dynamos commented
Can anybody merge this as required for #12103

2022-09-25 07:10 UTC, Grimler91 requested changes

2022-09-25 07:10 UTC, Grimler91 commented on packages/opencolorio/build.sh
> +TERMUX_PKG_EXTRA_CONFIGURE_ARGS="-Dpystring_INCLUDE_DIR=/data/data/com.termux/files/usr/lib/ -DOCIO_BUILD_PYTHON=off"
Use $TERMUX_PREFIX instead of /data/data/com.termux/files/usr, we do not want to hardcode the prefix string

2022-09-30 12:24 UTC, T-Dynamos commented
Not merged yet?

2022-09-30 18:57 UTC, merged

2022-09-30 19:05 UTC, Grimler91 commented
Thanks!