add(main): new package robin-map
termux/termux-packages pull request #11710
Opened 2022-08-24 11:50 UTC by T-Dynamos

#11674

2022-08-26 14:14 UTC, sylirre commented
Instead of adding one-by-one each of Blender dependency, please add them in one pull request. Just to note that if Blender packaging will be failed, the standalone library packages will be mostly useless.

2022-10-01 16:06 UTC, Grimler91 requested changes

2022-10-01 16:06 UTC, Grimler91 commented on packages/robin-map/build.sh
> +TERMUX_PKG_DESCRIPTION="C++ implementation of a fast hash map and hash set using robin hood hashing "
Please remove extra space at end of description

2022-10-09 08:17 UTC, T-Dynamos commented
Please merge this

2022-10-09 10:02 UTC, merged

2022-10-09 10:04 UTC, Grimler91 commented
Thanks!