New package: testssl.sh
termux/termux-packages pull request #11734
Opened 2022-08-27 16:20 UTC by ifurther

Closes  #11699

2022-08-28 00:54 UTC, 2096779623 requested changes
Please add `TERMUX_PKG_PLATFORM_INDEPENDENT=true` .

2022-08-29 12:59 UTC, ifurther commented
I fixed.

2022-09-01 11:03 UTC, ifurther commented
@sylirre I fixed.

2022-09-01 13:18 UTC, sylirre commented
I don't see that.

![still-has-issues](https://user-images.githubusercontent.com/107305601/187922386-290659e3-3635-4b1c-b223-a9dc68c6b3ae.png)

And that is only a part of what you need to fix. There lots of similar cases.

`$TERMUX_PREFIX` is valid under build environment, but not under Termux which uses `$PREFIX` instead. You shouldn't use this variable anyway and use full path instead.

Finally, I've asked about *patch* because such things must be reviewed before changes. `sed` is not reliable as doesn't distinguish entries which should be replaced and which should not.

2022-09-03 11:25 UTC, ifurther commented
@sylirre I add patch file and using full path

2022-09-03 20:33 UTC, sylirre commented on packages/testssl.sh/fix-hardcodepath.patch
> ++          exec 42>&2 2> >(tee @TERMUX_PREFIX@/tmp/testssl-$$.log | sed -u 's/^.*$/now/' | date -f - +%s.%N >/tmp/testssl-$$.time)
@ifurther The first part is fixed. What's up with second (`>/tmp/testssl-$$.time`)? There also numerous places for where other paths are not fixed.

2022-09-03 20:34 UTC, merged