upgpkg(main/libprotobuf): update to 3.21.5
termux/termux-packages pull request #11741
Opened 2022-08-28 08:10 UTC by zorro

2022-08-28 10:21 UTC, 2096779623 approved these changes

2022-08-29 13:15 UTC, 2096779623 requested changes
Remove `TERMUX_PKG_REVISION` .

2022-08-29 14:01 UTC, zorro commented
> Remove `TERMUX_PKG_REVISION` .

Done

2022-08-30 05:07 UTC, 2096779623 approved these changes

2022-08-31 19:24 UTC, merged