add(x11): new package eww
termux/termux-packages pull request #11975
Opened 2022-09-18 03:28 UTC by T-Dynamos

Closes #11940

2022-09-20 11:17 UTC, T-Dynamos commented
Please merge this also, I need it!

2022-09-20 11:19 UTC, OrdinaryEnder commented
Ewwwwwwww

2022-09-20 11:24 UTC, Grimler91 requested changes

2022-09-20 11:24 UTC, Grimler91 commented on x11-packages/eww/fix_tmp_hardcoded_path.patch
> ++            .unwrap_or_else(|_| std::path::PathBuf::from("/data/data/com.termux/files/usr/tmp"))
Please use @TERMUX_PREFIX@ in patches

2022-09-20 13:58 UTC, T-Dynamos commented
@Grimler91

2022-09-21 19:29 UTC, merged

2022-09-21 19:30 UTC, Grimler91 commented
Thanks!