libfcl: disable octomap dependency
termux/termux-packages pull request #12232
Opened 2022-10-01 13:22 UTC by pvonmoradi

https://github.com/termux/termux-packages/issues/12219

2022-10-01 15:31 UTC, Grimler91 requested changes
Please set TERMUX_PKG_REVISION=1 as well

2022-10-01 16:08 UTC, pvonmoradi commented
> Please set TERMUX_PKG_REVISION=1 as well

ok but why the static libs are built for octomap (`octomath.a` and `octomap.a`) but they are not available when `libfcl` is being built?

2022-10-01 16:58 UTC, Grimler91 commented
They are in [octomap-static](https://packages.termux.dev/apt/termux-main/pool/main/o/octomap-static/), if they are required you can add octomap-static to libfcl's `TERMUX_PKG_BUILD_DEPENDS`

2022-10-09 02:02 UTC, thunder-coding approved these changes

2022-10-09 02:03 UTC, merged