New package:cbonsai
termux/termux-packages pull request #12306
Opened 2022-10-09 07:46 UTC by Anonymous1231-dev

2022-10-09 07:50 UTC, Anonymous1231-dev commented
>2022-10-09T07:48:55.0035845Z termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libvulkan.so'
2022-10-09T07:48:55.0036440Z termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libz.so'
2022-10-09T07:48:55.1361130Z ERROR: No files in package.

WHAT?

2022-10-09 08:15 UTC, Grimler91 requested changes
Makefile needs to be patched to use $CC instead of hardcoded cc, and to not override PREFIX

2022-10-09 08:15 UTC, Grimler91 commented on packages/cbonsai/build.sh
> +TERMUX_PKG_DEPENDS="ncurses, ncurses-static, ncurses-ui-libs, ncurses-ui-libs-static, ncurses-utils"
Static packages are most likely not (runtime) dependencies

2022-10-10 06:58 UTC, Anonymous1231-dev commented
@Grimler91 , the build use $C instead of $CC, how?

2022-10-10 06:58 UTC, Anonymous1231-dev commented
@Grimler91 , the build use $C instead of $CC, how?

2022-10-10 07:02 UTC, Grimler91 commented
> @Grimler91 , the build use $C instead of $CC, how?

Makefiles uses a slightly different format, so needs to be `$(CC)` instead of `$CC`

2022-10-10 07:12 UTC, Anonymous1231-dev commented
site down... :(

2022-10-10 07:12 UTC, Anonymous1231-dev commented
site down... :(

2022-10-10 07:22 UTC, Anonymous1231-dev commented
Can someone ru-run the actions?

2022-10-10 08:08 UTC, Anonymous1231-dev commented
>Makefile:2: *** Recursive variable 'CC' references itself (eventually).  Stop.

Oops

2022-10-11 00:54 UTC, Anonymous1231-dev commented
Done!

2022-10-11 07:19 UTC, Anonymous1231-dev commented
Can someone merge it?

2022-10-12 06:38 UTC, Anonymous1231-dev commented
@Grimler91 ready to merge!

2022-10-12 06:48 UTC, Grimler91 commented
@Anonymous1231-dev Please re-write the commit message currently it reads:

```
New package:cbonsai

Signed-off-by: Anonymous1231-dev <87801676+Anonymous1231-dev@users.noreply.github.com>

Fix(1th attempt)

Signed-off-by: Anonymous1231-dev <87801676+Anonymous1231-dev@users.noreply.github.com>

Update deps

Signed-off-by: Anonymous1231-dev <87801676+Anonymous1231-dev@users.noreply.github.com>

Patch

Signed-off-by: Anonymous1231-dev <87801676+Anonymous1231-dev@users.noreply.github.com>

Fixed Patch

Signed-off-by: Anonymous1231-dev <87801676+Anonymous1231-dev@users.noreply.github.com>

fix

Signed-off-by: Anonymous1231-dev <87801676+Anonymous1231-dev@users.noreply.github.com>

Fix patch again

Signed-off-by: Anonymous1231-dev <87801676+Anonymous1231-dev@users.noreply.github.com>
```

which is a bit excessive. First line and (optionally) one `Signed-off-by:` would suffice

2022-10-12 10:05 UTC, Anonymous1231-dev commented
Done!

2022-10-12 11:40 UTC, merged

2022-10-12 11:40 UTC, Grimler91 commented
Thanks!