add package: perl-rename
termux/termux-packages pull request #12369
Opened 2022-10-15 01:07 UTC by ELWAER-M

2022-10-15 19:00 UTC, ELWAER-M commented on packages/perl-rename/build.sh
> +    find $TERMUX_PKG_MASSAGEDIR -type f -name rename* -execdir sh -c 'mv {} $(echo {} | sed "s|rename|perl-rename|")' \;
done

2022-10-17 17:14 UTC, ELWAER-M commented
ok i changed them

2022-10-22 20:00 UTC, Grimler91 requested changes
Package contains an essentially empty folder `/data/data/com.termux/files/usr/lib/x86_64-linux-gnu/`, it should be removed

2022-10-24 00:01 UTC, ELWAER-M commented on packages/perl-rename/build.sh
> +	find $TERMUX_PKG_MASSAGEDIR -type f -name "rename*" -execdir sh -c 'mv {} $(echo {} | sed "s|rename|perl-rename|")' \;
its not for the binary only its also for the manual pages too, i think its better to do that in just one command

2022-11-01 20:21 UTC, merged

2022-11-01 20:21 UTC, Grimler91 commented on packages/perl-rename/build.sh
> +	find $TERMUX_PKG_MASSAGEDIR -type f -name "rename*" -execdir sh -c 'mv {} $(echo {} | sed "s|rename|perl-rename|")' \;
Good point, thanks for pointing that out

2022-11-01 20:21 UTC, Grimler91 commented
Thanks!