enhance(recoll): configure without --disable-python-module
termux/termux-packages pull request #12497
Opened 2022-10-23 10:33 UTC by JCGoran

This PR builds on #12299 to enable Python support in the recoll package. Hopefully also fixes https://github.com/koniu/recoll-webui/issues/86.

2022-10-23 10:36 UTC, 2096779623 requested changes
Thanks for the PR!
* Please bump revision (`TERMUX_PKG_REVISION=1`)
* Try specifying python version without hardcoded paths, example: https://github.com/termux/termux-packages/blob/0281a1c1e251e5c20072187b037493d77e7c3679/packages/z3/build.sh#L13

2022-10-24 10:22 UTC, JCGoran commented
> Thanks for the PR!
> 
> * Please bump revision (`TERMUX_PKG_REVISION=1`)
> 

Done.

> * Try specifying python version without hardcoded paths, example: https://github.com/termux/termux-packages/blob/0281a1c1e251e5c20072187b037493d77e7c3679/packages/z3/build.sh#L13

Done, now the patching isn't necessary.

P.S. I didn't know whether you'd prefer me to push additional commits, or rebase, so I opted for the first one, but I can squash it into one commit if you'd prefer.

2022-10-24 10:29 UTC, 2096779623 commented
Good! need to reword this commit, add `recoll` in front or squash :) .

2022-10-24 14:48 UTC, JCGoran commented
Rebased on latest master and squashed into one commit.

2022-10-24 14:49 UTC, 2096779623 approved these changes
Thanks!

2022-10-24 14:50 UTC, merged