add(main): new package gomp
termux/termux-packages pull request #14278
Opened 2022-12-31 04:52 UTC by T-Dynamos

2022-12-31 05:51 UTC, 2096779623 requested changes
![image](https://user-images.githubusercontent.com/57583560/210126635-b25b90d1-e911-4e76-90ea-993bd05044c0.png)

Hardcoded path here: https://github.com/aditya-K2/gomp/blob/0c0cbbf950c84f44092dbeb70d3ae2c095b79b9e/config/config.go#L116-L117

2022-12-31 11:41 UTC, 2096779623 requested changes
It should depend on `mpd` .

2022-12-31 12:47 UTC, 2096779623 commented
![Screenshot_20221231-204434](https://user-images.githubusercontent.com/57583560/210137187-3df33942-4fad-4088-af05-051025a3db8b.png)

It finally worked after I searched for the play button for half an hour....

2023-01-01 17:41 UTC, PraveenNanda124 reviewed
Great work

2023-01-02 04:09 UTC, T-Dynamos commented on packages/gomp/build.sh
> +TERMUX_PKG_SRCURL=git+https://github.com/aditya-K2/gomp
> The Git URL specification isn't valid either. Must be a `https://github.com/aditya-K2/gomp.git`
Ah this changed, see PR #14281

2023-01-08 02:06 UTC, merged