tcc : fix arm build
termux/termux-packages pull request #16413
Opened 2023-04-24 21:42 UTC by be2020

* armv7a (androideabi) config fixed
* obsolete patches removed
* add ndk-sysroot dependency (needed to use the compiler)

Note:
- patch was NOT tested under the termux package system really
- however the tcc configuration was tested for armv7a to produce a working package that, when installed on device, can compile tcc again and pass the tests. As in

  git clone git://repo.or.cz/tinycc.git cd tinycc ./configure --cc=tcc make && make test

2023-06-10 13:52 UTC, 2096779623 requested changes

2023-06-10 13:52 UTC, 2096779623 commented on packages/tcc/build.sh
> +        echo "configuring later..."
Don't need this line.

2023-07-05 09:18 UTC, xtkoba commented
I won't accept changes that are not tested.

2023-07-05 09:18 UTC, closed without merging

2023-07-05 10:28 UTC, xtkoba commented
What is more problematic is that the description is deceptive. This is actually a version bump, not just a fix. I can hardly accept it.

2023-07-05 11:40 UTC, xtkoba commented
You should separate the commits of

* fix
* version bump
* refactoring

between one another. Everything in one commit is hard to review.

2023-07-05 17:39 UTC, be2020 commented
Well, if you find that the patch suggests to remove a lot of lines that according to the commit message were written by yourself, then you are right, but then again you should know better than me what these were meant to do ;)