enhance(main/bc): Change to gavinhoward/bc
termux/termux-packages pull request #16516
Opened 2023-05-02 02:31 UTC by gavinhoward

This commit/PR is a request to consider changing the bc implementation to the one by Gavin Howard. I understand if this PR is ultimately rejected.

That said, the bc/dc by Gavin Howard (me) is IMO a better option than the GNU bc/dc for these reasons:

* It is already used by the upstream Android Open Source Project. [1]
* It is permissively licensed.
* It implements the POSIX bc standard better.
* It can be made to imitate the GNU bc/dc exactly, barring differences between the GNU bc and the POSIX standard. This includes all GNU extensions and command-line options.
* It can *also* be made to imitate the BSD bc/dc exactly, barring differences between the BSD bc and the POSIX standard. This means that my bc can be a bridge for Android users used to the BSD bc/dc.
* It is being actively maintained, and I respond to bug reports. [2]
* It is *much* faster. [3]
* It has many more extensions, most of which are math-related. [4] [5]
* I am prepared to be the maintainer of this package like I maintain the Gentoo package, [6] though I am willing to let others maintain it.

I see two possible disadvantages:

* My bc/dc is takes more space.
* The GNU bc/dc is more well-known.

However, I don't think these are problems.

On aarch64, the size of the package is under 300 kB. This includes the manuals. Total space use would be about 1.2 MB. The extra space is also partially offset by having no dependency on flex.

Yes, the GNU bc/dc is more well-known, but I have tested my bc against the GNU bc from the beginning and achieved near-perfect compatibility. There have been few reports of discrepancies, and any reported discrepancies have been fixed if they do not violate the POSIX standard. This bc is also faster and has more extensions.

It is also becoming a standard itself. It has been the system bc for FreeBSD since 13.0 (April 2021), [7] and it became the system bc in Mac OSX starting with Ventura. [8] It is also supported in several Linux distros as the default or as a first-class alternative to the GNU bc.

My bc/dc also has built-in history support, but it can also use both readline and libedit instead. I chose readline for this package since the GNU bc already used it, but if the built-in history is used, then this bc has no runtime dependencies.

Now, for notes on the commit.

I put myself as the maintainer. It may be wrong because I couldn't find any examples that were not "@termux". The homepage is my self-hosted Gitea, but I use the GitHub link for ease.

I use a direct configure.sh call because it's a hand-coded script (not autotools) and does not recognize some default options.

I use an install step because I have a script from the musl project that installs, but I saw that policy was to use the `install` program.

The LICENSE.md file is not part of the install, so I added the step to install it.

Finally, this bc uses a raw Makefile (generated by configure.sh), but both together *do* support out-of-source builds.

[1]: https://android.googlesource.com/platform/external/bc/
[2]: https://github.com/gavinhoward/bc/issues/67
[3]: https://git.gavinhoward.com/gavin/bc#performance
[4]: https://git.gavinhoward.com/gavin/bc#extensions
[5]: https://git.gavinhoward.com/gavin/bc/src/branch/master/manuals/bc/A.1.md#extended-library
[6]: https://github.com/gentoo/gentoo/blob/master/sci-calculators/bc-gh/metadata.xml#L4-L7
[7]: https://man.freebsd.org/cgi/man.cgi?query=bc&sektion=1&manpath=FreeBSD+13.0-RELEASE#end
[8]: https://github.com/apple-oss-distributions/bc/tree/main/bc

2023-05-02 04:06 UTC, thunder-coding requested changes
Thanks, I've requested a few changes.

No objections from my side if your project is compatible with GNU bc. Although I think it would be better if we package your enhanced version of bc as a separate package, instead of replacing the current gnu-bc. The current package can be renamed to gnu-bc, and your version can be added as howard-bc (as how Alpine is packaging your implementation) or bc-gh (as used by Gentoo, and others)

2023-05-02 04:33 UTC, gavinhoward commented
Requested changes pushed.

> Although I think it would be better if we package your enhanced version of bc as a separate package, instead of replacing the current gnu-bc.

I apologize; I figured from the contributing guideline "**Not serving duplicated functionality**" that termux would only package one or the other.

I have taken the liberty of placing my `bc` in a separate `bc-gh` package and setting up the build such that it will be built as `bc-gh` and `dc-gh` so that it won't interfere with the GNU `bc`. (See the `EXECSUFFIX` environment variable on `configure.sh`.)

2023-05-02 05:00 UTC, gavinhoward commented
Silly me. Forgot to change the install step for the new name since that would have been taken care of by the `make install` command that we're not using.

2023-05-02 09:16 UTC, truboxl commented on packages/bc-gh/build.sh
> +TERMUX_PKG_HOSTBUILD=true
```suggestion
```
Not needed

2023-05-02 13:05 UTC, gavinhoward commented
Requested change pushed.

I also added the `--disable-nls` flag because the install does not install the locales; disabling it will save some space.

2023-05-02 18:49 UTC, agnostic-apollo commented
Didn't know it was being used by AOSP and as system package in other distros. README didn't mention it. ;)

>I apologize; I figured from the contributing guideline "Not serving duplicated functionality" that termux would only package one or the other.

We do allow duplicate functionality packages if they have separate useful features or enhancements/fixes, so yours does qualify, policy should probably make it clear. You will also be maintaining it yourself instead of termux devs and size is small, so even less reasons to deny approval. Having both packages is the way to go.

2023-05-02 19:51 UTC, gavinhoward commented
> Didn't know it was being used by AOSP and as system package in other distros. README didn't mention it. ;)

Ah, well, it's mostly small-time stuff, and AOSP is not exposed to end users. Sorry.

> You will also be maintaining it yourself instead of termux devs and size is small, so even less reasons to deny approval. Having both packages is the way to go.

I'm happy to maintain it, and happy to have it just be an option!

2023-05-02 20:38 UTC, agnostic-apollo commented
>Ah, well, it's mostly small-time stuff, and AOSP is not exposed to end users. Sorry.

No worries. Good luck in future for world domination.

>I'm happy to maintain it, and happy to have it just be an option!

Great. Thanks for the submission.

2023-05-03 11:27 UTC, truboxl approved these changes

2023-06-10 13:49 UTC, 2096779623 commented
Please keep the latest upstream and then update the version to `6.6.0` .

It's released more actively, I recommend turning on automatic updates for this package.
https://github.com/termux/termux-packages/wiki/Auto-updating-packages

2023-06-11 01:07 UTC, gavinhoward commented
I didn't know if I should change the PR without input. I'll keep it up to date. Sorry.

I ran the check auto update script before submitting; it didn't work. I don't want to risk a bad update by doing auto update anyway, so I decided to update by hand since I am upstream.

2023-06-13 06:53 UTC, merged

2023-06-13 07:02 UTC, agnostic-apollo commented
Thanks for updating to new version,  and you can change your own PRs, no apologies needed. Not sure why this wasn't merged before. Did basic test on arm64 and both are working. It's perfectly fine if you want to manage updates yourself, just send a pull request when needed.

Package is now available on our primary repo at https://packages.termux.dev/apt/termux-main/pool/main/b/bc-gh/ and will be available on other mirrors when they sync. You can switch mirrors with `termux-change-repo`. Sorry, couldn't keep your signed commit due to rebase against master.

2023-06-13 07:05 UTC, gavinhoward commented
Thank you!

The lack of signed commit is not a problem. My Git config doesn't let me *not* sign, but it's not that important in external repos.

2023-06-13 07:09 UTC, agnostic-apollo commented
You are very welcome!

Ah, okay, cool.

2023-06-13 07:09 UTC, truboxl commented
@agnostic-apollo I wasnt brave enough to press the merge button

2023-06-13 07:15 UTC, agnostic-apollo commented
Ah, I am sure it wouldn't have been a "what does thiiis button do..." situation if you did. ;)