fix(main/nushell): change `--features=extra` to `--features=dataframe` as former is obsolete
termux/termux-packages pull request #16634
Opened 2023-05-14 09:04 UTC by stevenxxiu

See https://www.nushell.sh/blog/2022-11-29-nushell-0.72.html.

2023-05-14 12:01 UTC, thunder-coding requested changes
Hey, thanks for the PR. Looks great, just a small one-line change requested. And thanks for going through the nushell changelog and noticing that!

2023-05-14 13:46 UTC, stevenxxiu commented on packages/nushell/build.sh
Thanks, done.

2023-05-14 14:20 UTC, thunder-coding approved these changes

2023-05-14 14:54 UTC, stevenxxiu commented
Hmm the build error appears to be due to https://github.com/simd-lite/simd-json/issues/263. Should I just skip the extra features for `arm`?

2023-06-08 12:57 UTC, stevenxxiu commented
I skipped the extra features for `arm` before, so it should build. Anything else I need to do?

2023-07-04 10:25 UTC, landfillbaby commented
reenabled `--features=extra`. see https://www.nushell.sh/blog/2023-06-27-nushell_0_82.html#continuing-cratification-effort

2023-07-05 10:49 UTC, merged