bump(main/starship): v1.15.0
termux/termux-packages pull request #16868
Opened 2023-06-08 07:19 UTC by AminurAlam

0001-Cargo.toml.patch: updated patch
build.sh: `$CARGO_HOME/registry/src/github*/cmake-*` -> `$CARGO_HOME/registry/src/*/cmake-*`

fixes #16853

2023-06-09 04:36 UTC, 2096779623 requested changes

2023-06-09 10:27 UTC, 2096779623 approved these changes
Thanks!

2023-06-09 11:02 UTC, AminurAlam commented
the workflow has been running for an hour??
the first one finished in just 11 mins

2023-06-09 12:03 UTC, finagolfin commented
You need to rebase, else it will build all packages that were updated in trunk too.

I've canceled the current build, just rebase and push and it will only build your package.

2023-06-09 12:18 UTC, 2096779623 commented
If you don't know how to rebase upstream, here are some tips:
```bash
# git your fork first 
git remote add upstream https://github.com/termux/termux-packages
git pull upstream master --rebase
git push origin starship -f
```
GitHub also provides a handy button:
![image](https://github.com/termux/termux-packages/assets/57583560/e488f21e-d652-4932-a0cc-cd4f603a450b)
Whoever clicks this button will add that person as a co-author to all commits of this pr by default (the existing ones will not).

2023-06-10 13:27 UTC, 2096779623 commented
emm, don't just click `Update Branch`, if you want, I can help you update the upstream.

2023-06-10 13:38 UTC, merged