addpkg(main/far2l): FAR Manager v2 - Linux port
termux/termux-packages pull request #17379
Opened 2023-07-06 07:52 UTC by spvkgn

2023-07-06 12:23 UTC, 2096779623 commented
I suggest you to use [this patch](https://github.com/termux/termux-packages/blob/3c291eb3b2e3859df8f4563ef47280e1568ca497/packages/7zip/disable_hardware_acceleration_support_on_arm.patch#L39) to fix arm build.

2023-07-14 08:22 UTC, truboxl requested changes
This package should be moved to `x11-packages`

2023-07-15 23:28 UTC, truboxl commented
I will help rebasing branch since CI got polluted

2023-07-22 18:21 UTC, truboxl requested changes

2023-07-22 18:21 UTC, truboxl commented on x11-packages/far2l/build.sh
> +TERMUX_PKG_REVISION=1
```suggestion
```
Not needed

2023-07-22 18:21 UTC, truboxl commented on x11-packages/far2l/build.sh
> +TERMUX_PKG_DEPENDS="libc++, libarchive, libuchardet, pcre"
```suggestion
TERMUX_PKG_DEPENDS="libarchive, libc++, libuchardet, pcre"
```

2023-07-22 18:21 UTC, truboxl commented on x11-packages/far2l/build.sh
> +-DCMAKE_BUILD_TYPE=Release
```suggestion
```
Not needed

2023-07-22 18:21 UTC, truboxl commented on x11-packages/far2l/far2l-plugins-netrocks.subpackage.sh
> +TERMUX_SUBPKG_DEPENDS="libneon, libnfs, libssh, openssl, samba"
```suggestion
TERMUX_SUBPKG_DEPENDS="libc++, libneon, libnfs, libssh, openssl, samba"
```

2023-07-22 18:21 UTC, truboxl commented on x11-packages/far2l/far2l-ttyxi.subpackage.sh
> +TERMUX_SUBPKG_DEPENDS="libxi"
```suggestion
TERMUX_SUBPKG_DEPENDS="libc++, libx11, libxi"
```

2023-07-22 18:21 UTC, truboxl commented on x11-packages/far2l/build.sh
> +TERMUX_PKG_DESCRIPTION="FAR Manager v2 - Linux port"
```suggestion
TERMUX_PKG_DESCRIPTION="FAR Manager v2"
```
I think a general description is enough

2023-07-25 20:40 UTC, truboxl approved these changes
So far LGTM thanks! Hopefully you can upstream your patches.

I will help squash and merge if others have no more reviews.

2023-07-28 11:20 UTC, merged