new package: ices
termux/termux-packages pull request #17425
Opened 2023-07-13 15:56 UTC by ErSoul

2023-07-14 09:29 UTC, truboxl requested changes
`TERMUX_PKG_REVISION` is not needed. Also preferably add a newline at the end of each file.

2023-07-14 09:29 UTC, truboxl commented on packages/ices/build.sh
> +TERMUX_PKG_REVISION=1
```suggestion
```

2023-07-14 09:29 UTC, truboxl commented on packages/libshout/build.sh
> +TERMUX_PKG_REVISION=1
```suggestion
```

2023-07-15 09:01 UTC, Grimler91 requested changes
Please split the commit into two: I don't think "new package: ices" describe the changes done, since another new package, libshout is added as well.

Use one commit for each package

2023-07-16 03:34 UTC, ErSoul commented on packages/ices/build.sh
> +
Just added the two commits. Also renamed the PR...

2023-07-16 09:26 UTC, closed without merging

2023-07-16 09:26 UTC, Grimler91 commented
Thanks!

2023-07-16 09:27 UTC, Grimler91 commented
Merged in https://github.com/termux/termux-packages/commit/7ec7ae519c2b02ada6df6362272aff165d96e724, but github's UI failed to detect it..