Add rizin
termux/termux-packages pull request #18275
Opened 2023-10-15 15:12 UTC by AbhiTheModder

This pull request adds support for rizin(fork of radare2), a UNIX-like reverse engineering framework and commandline toolset, to the android termux package. Rizin aims to provide a more user-friendly and modular interface, as well as faster development and bug fixes. With this package, termux users can easily install and use rizin on their android devices, and perform various tasks such as binary analysis, debugging, forensics, and exploitation. The package has been tested on several android versions and architectures and works as expected. I hope this contribution will be useful for the termux community and the rizin project.

and a big thanks to @TomJo2000... I basically took a day of him, but he still helped me. ❤

2023-10-15 17:08 UTC, finagolfin commented
Any reason you are not the maintainer?

2023-10-15 17:11 UTC, AbhiTheModder commented
> Any reason you are not the maintainer?

@finagolfin none, if given so I can be the maintainer also. I used @termux  in maintainer as I seen in most of packages and even in example of radare2, that's why.

2023-10-15 18:57 UTC, Grimler91 requested changes
Please rebase and squash the commits against the master branch. 
Right now the PR adds 7 commits, out of which 4 just say `Update build.sh` and `Merge branch 'termux:master' into master`. It should be enough with one commit to add one package

2023-10-15 18:57 UTC, Grimler91 commented on packages/rizin/build.sh
> +# Thank you @TomJo2000
Please remove this comment. You can put TomJo as co-developer instead in commit message, like:

```
rizin: add package

Co-developed-by: Joshua Kahn @TomJo2000
```

2023-10-15 18:57 UTC, Grimler91 commented on packages/rizin/build.sh
> +TERMUX_PKG_SHA256=ab4bd4c767940b28d683f664f27180665f98bfab2aa7972ba4c331e8bed30da8
Please add newline at end of file

2023-10-15 18:57 UTC, Grimler91 commented on packages/rizin/build.sh
> +TERMUX_PKG_DESCRIPTION="UNIX-like reverse engineering framework and command-line toolset. (fork of radare2)"
I think we can remove the `(fork of radare2)` comment, the project should hopefully be recognizable on its own

2023-10-16 01:46 UTC, closed without merging

2023-10-16 02:01 UTC, AbhiTheModder commented
@Grimler91 Sure thanks and it seems I was directly pushing changes through master branch of my fork that's why I was facing issues during rebasing

Doing it in another branch. Sorry for the troubles

Thanks