postgresql: build btree_gin
termux/termux-packages pull request #19780
Opened 2024-04-15 20:44 UTC by aicynide

Build btree_gin extension

2024-04-17 09:17 UTC, truboxl requested changes
Change your whitespaces to tabs and bump TERMUX_PKG_REVISION

2024-04-18 23:04 UTC, truboxl commented
Please fix your tabbing

2024-04-18 23:15 UTC, TomJo2000 commented
All Shell scripts (`.sh` files) should be indented using tabs, as per the coding guidelines.
(Apparently we do not specify a tab width for them, but 4 is customary for `build.sh` files)
https://github.com/termux/termux-packages/wiki/Coding-guideline#script-formatting

We also provide a [`.editorconfig` file in the repo](https://github.com/termux/termux-packages/blob/master/.editorconfig), to automatically apply these guidelines,
please make sure your editor is properly using it.
For additional information see: https://editorconfig.org/

2024-04-19 11:10 UTC, TomJo2000 commented
That's just a web version of VS Code, so that does support Editorconfig, with a plugin.

2024-04-19 15:14 UTC, truboxl commented on packages/postgresql/build.sh
> +                btree_gin \
```suggestion
		btree_gin \
```

2024-04-20 04:06 UTC, TomJo2000 commented
It seems to be building, but the commits are a mess.
We ***can*** squash that together during merge,
but we usually prefer the PR author to keep their commit(s) organized.

You have stated that you are using GitHub Web on a mobile phone to make this PR, so I'm inclined to be more lenient on commit cleanliness, I am still going to complain about it though.

---

More importantly, testing would be appreciated for the PR.

<sup>(This is a pre-written, saved reply.)</sup>
If you want to test this PR please download the appropriate DEB package(s)
from the build artifacts of the [associated PR's latest CI run](https://github.com/termux/termux-packages/pull/19780/checks).
![image](https://github.com/termux/termux-packages/assets/43716232/c13f4982-8fcf-47fb-8725-dd0dcdde2731)
As far as I am aware build artifact downloads are not available through the GitHub mobile app,
so you will need to open this PR in the browser to download them.

After downloading the build artifact, make sure to `unzip` and un-`tar` it.
<details><summary>Detailed instructions, if needed.</summary>
<p>

```bash
# finding out what architecture you need
# architecture is just below the TERMUX_VERSION
termux-info

# e.g.
# [...]
# TERMUX_MAIN_PACKAGE_FORMAT=debian
# TERMUX_VERSION=0.118.0
# TERMUX__USER_ID=0
# Packages CPU architecture:
# aarch64
# [...]

# =======================

# make sure `unzip` and `tar` are installed using
pkg install unzip tar

# unzip the artifact (if you have a different architecture this might be arm, i686 or x86_64 instead)
unzip debs-aarch64-*.zip

# untar the artifact
tar xf debs-aarch64-*.tar

# You should now have a debs/ directory in your current working directory
# Install the packages from the local source using
pkg install -- ./debs/*.deb

# to clean up, you can remove the debs/ directory, .tar file and .zip file
rm -rfi debs debs-aarch64-*.zip debs-aarch64-*.tar
```

</p>
</details>

2024-04-21 03:46 UTC, truboxl approved these changes
Nvm. I will squash it.

2024-04-21 03:50 UTC, merged