scripts(bin/update-checksum): support for array SHA-256
termux/termux-packages pull request #20645
Opened 2024-06-23 09:38 UTC by tqfx

2024-06-23 09:48 UTC, tqfx commented
See #20529

2024-06-23 16:58 UTC, truboxl commented on scripts/bin/update-checksum
> +			sed -i "s|${checksum[i]}|${new_checksum[i]}|" "${buildsh_path}"
This breaks the old way of quickly populate empty or replace invalid `TERMUX_PKG_SHA256=` when prototyping `build.sh`

2024-06-24 13:35 UTC, tqfx commented
Work with case 1

```sh
TERMUX_PKG_VERSION=2.8.7
TERMUX_PKG_SRCURL=(https://github.com/ArtalkJS/Artalk/archive/v${TERMUX_PKG_VERSION}.tar.gz
                   https://github.com/ArtalkJS/Artalk/releases/download/v${TERMUX_PKG_VERSION}/artalk_ui.tar.gz)
TERMUX_PKG_SHA256=
```

Work with case 2

```sh
TERMUX_PKG_VERSION=2.8.7
TERMUX_PKG_SRCURL=(https://github.com/ArtalkJS/Artalk/archive/v${TERMUX_PKG_VERSION}.tar.gz
                   https://github.com/ArtalkJS/Artalk/releases/download/v${TERMUX_PKG_VERSION}/artalk_ui.tar.gz)
TERMUX_PKG_SHA256=invalid
```

Work with case 3

```sh
TERMUX_PKG_VERSION=2.8.7
TERMUX_PKG_SRCURL=(https://github.com/ArtalkJS/Artalk/archive/v${TERMUX_PKG_VERSION}.tar.gz
                   https://github.com/ArtalkJS/Artalk/releases/download/v${TERMUX_PKG_VERSION}/artalk_ui.tar.gz)
TERMUX_PKG_SHA256=(
invalid
)
```

Work with case 4

```sh
TERMUX_PKG_VERSION=2.8.7
TERMUX_PKG_SRCURL=https://github.com/ArtalkJS/Artalk/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=
```

Work with case 5

```sh
TERMUX_PKG_VERSION=2.8.7
TERMUX_PKG_SRCURL=https://github.com/ArtalkJS/Artalk/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=invalid
```

Work with case 6

```sh
TERMUX_PKG_VERSION=2.8.7
TERMUX_PKG_SRCURL=https://github.com/ArtalkJS/Artalk/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=(
invalid
)
```

2024-07-01 19:35 UTC, TomJo2000 requested changes
Just found this PR now.
There's a bit of clean up I'd like to do on this,
other than my couple nitpicks, great work.

2024-07-01 19:35 UTC, TomJo2000 commented on scripts/bin/update-checksum
> +			for ((i=0; i<${#new_checksum[@]}; ++i)) do
We can turn this entire for loop into a single `printf`
e.g.
```suggestion
			checksum+="$( printf '\t%s\n' "${new_checksum[@]}" )"
```

2024-07-01 19:35 UTC, TomJo2000 commented on scripts/bin/update-checksum
> +		if [ ${#new_checksum[@]} -gt 1 ]; then
```suggestion
		if (( ${#new_checksum[@]} > 1 )); then
```

2024-07-01 19:35 UTC, TomJo2000 commented on scripts/bin/update-checksum
>  	# Calculate new checksum in subshell.
This comment could use an update.
```suggestion
	# Command substitution create a subshell, we want to do this 
	# to not effect the main scope's variables by sourcing the build script
```
Something along these lines, feel free to come up with something less wordy.

2024-07-01 19:35 UTC, TomJo2000 commented on scripts/bin/update-checksum
> +		for url in ${TERMUX_PKG_SRCURL[@]}; do
This should be quoted.
https://www.shellcheck.net/wiki/SC2068
```suggestion
		for url in "${TERMUX_PKG_SRCURL[@]}"; do
```

2024-07-01 19:35 UTC, TomJo2000 commented on scripts/bin/update-checksum
>  	if [ -n "${new_checksum}" ]; then
That's an array now.
Also prefer using arithmetic evaluation for a null length check.
```suggestion
	if (( ${#new_checksum[@]} )); then
```

2024-07-01 19:35 UTC, TomJo2000 commented on scripts/bin/update-checksum
> +			if [ -n "${dl_tmpdir}" ] && [ -d "${dl_tmpdir}" ]; then
The `-n` test is redundant.
Also prefer `[[` bash test `]]`.
```suggestion
			if [[ -d "${dl_tmpdir}" ]]; then
```

2024-07-01 19:35 UTC, TomJo2000 commented on scripts/bin/update-checksum
> +				if [ -f "${dl_tmpdir}/source-bundle" ]; then
Prefer `[[` bash test `]]`.
```suggestion
				if [[ -f "${dl_tmpdir}/source-bundle" ]]; then
```

2024-07-01 19:35 UTC, TomJo2000 commented on scripts/bin/update-checksum
> +				if ! curl --fail --location --retry 3 --output "${dl_tmpdir}/source-bundle" \
<sub>(Nitpick, feel free to ignore)</sub>
Not a big fan of this being split here.
```suggestion
				if ! curl --fail --location --retry 3 --output "${dl_tmpdir}/source-bundle" "$url"; then
```
Either keep it on 1 line, or split it after `--retry 3`.

2024-07-02 05:09 UTC, truboxl commented
Breaks for opencv. Probably that build.sh need to be rewritten.

2024-07-02 05:35 UTC, TomJo2000 commented
> Breaks for opencv. Probably that build.sh need to be rewritten.

Yep, at least the srcurl and sha256.

2024-07-02 05:55 UTC, TomJo2000 commented
looks like we have a couple more of these.
A cursory `rg -Hni '\+=\(' {x11-,root-,}packages` points out:
- `x11-packages/opencv`
<sup> already handled</sup>
- `x11-packages/virglrenderer-android/`
<sup> already handled</sup>
- `packages/unar`
- `packages/libmusicbrainz`
- `packages/softethervpn`
- `packages/asymptote`
- `packages/maxima`
- `packages/alist`
- `packages/ldc`

2024-07-02 06:05 UTC, TomJo2000 commented
Wait a minute, do we not care about this for `TERMUX_PKG_VERSION`?
I think if we're "fixing" it for `TERMUX_PKG_SRCURL` and `TERMUX_PKG_SHA256` we should phase out `+=(` for `TERMUX_PKG_VERSION` as well.

2024-07-02 06:08 UTC, tqfx commented
Okay. I'm going to modify them.

2024-07-02 13:06 UTC, tqfx commented
If `TERMUX_PKG_VERSION` is a string, auto-updates will work. If `TERMUX_PKG_VERSION` is an array, things get a little more complicated. See [ldc](https://github.com/termux/termux-packages/blob/master/packages/ldc/build.sh). For this case I tend to override `termux_pkg_auto_update` in `build.sh`.

2024-07-02 13:58 UTC, TomJo2000 commented
> If `TERMUX_PKG_VERSION` is a string, auto-updates will work. If `TERMUX_PKG_VERSION` is an array, things get a little more complicated. See [ldc](https://github.com/termux/termux-packages/blob/master/packages/ldc/build.sh). For this case I tend to override `termux_pkg_auto_update` in `build.sh`.

Good point.
A version array would complicate auto-updates.

2024-07-02 16:59 UTC, TomJo2000 requested changes
Sorry for spamming your email.
I took the opportunity to turn this review into generalized cleanup for these packages.

2024-07-02 16:59 UTC, TomJo2000 commented on disabled-packages/mingw-w64-crt/build.sh
No need to update disabled packages.
I won't comment on the rest of them.

2024-07-02 16:59 UTC, TomJo2000 commented on packages/aapt/build.sh
> +	https://android.googlesource.com/platform/frameworks/base
I guess not having the starting or closing parenthesis on the same line makes automatically updating it a lot easier.

If we wanna start enforcing that, that actually lets me simplify the package linter a bit.

2024-07-02 16:59 UTC, TomJo2000 commented on packages/artalk/build.sh
> -termux_pkg_auto_update() {
So this is able to be handled by the standard auto-update function now?

2024-07-02 16:59 UTC, TomJo2000 commented on packages/asymptote/build.sh
> +	2.89
Comments to note which version is for what would be nice like some other packages have.

2024-07-02 16:59 UTC, TomJo2000 commented on packages/asymptote/build.sh
> +	https://downloads.sourceforge.net/asymptote/asymptote-${TERMUX_PKG_VERSION}.src.tgz
Explicitly use index `[0]` to show that it's an array.
<sup>Also I'm pretty sure Shellcheck yells at you for not indexing on arrays</sup>
```suggestion
	https://downloads.sourceforge.net/asymptote/asymptote-${TERMUX_PKG_VERSION[0]}.src.tgz
```

2024-07-02 16:59 UTC, TomJo2000 commented on packages/groovy/build.sh
>  _JLINE_VERSION=2.14.6
If we're doing it for all these other packages,
we may as well fold these into a `TERMUX_PKG_VERSION=(...)` array.
The `_JANSI_TAGNAME` and `_JLINE2_TAGNAME` abstractions are probably still useful to keep though.

2024-07-02 16:59 UTC, TomJo2000 commented on packages/ldc/build.sh
> +		#	 ^
I don't think that should have been modified.

2024-07-02 16:59 UTC, TomJo2000 commented on packages/libmusicbrainz/build.sh
> +	https://github.com/metabrainz/libmusicbrainz/releases/download/release-${TERMUX_PKG_VERSION}/libmusicbrainz-${TERMUX_PKG_VERSION}.tar.gz
I can hear Shellcheck yelling at you.
```suggestion
	https://github.com/metabrainz/libmusicbrainz/releases/download/release-${TERMUX_PKG_VERSION[0]}/libmusicbrainz-${TERMUX_PKG_VERSION[0]}.tar.gz
```

2024-07-02 16:59 UTC, TomJo2000 commented on packages/maxima/build.sh
> +	https://downloads.sourceforge.net/sourceforge/maxima/Maxima-source/$TERMUX_PKG_VERSION-source/maxima-$TERMUX_PKG_VERSION.tar.gz
```suggestion
	https://downloads.sourceforge.net/sourceforge/maxima/Maxima-source/${TERMUX_PKG_VERSION[0]}-source/maxima-${TERMUX_PKG_VERSION[0]}.tar.gz
```

2024-07-02 16:59 UTC, TomJo2000 commented on packages/maxima/build.sh
> +
It looks like your formatter is taking out some tabs on occasion.
In this case, that's good though.
I'm not sure how this ever passed the trailing whitespace check.

2024-07-02 16:59 UTC, TomJo2000 commented on packages/ncurses/build.sh
> +	6.4.20231001
Comments would be nice here while we're at it.

2024-07-02 16:59 UTC, TomJo2000 commented on packages/perl/build.sh
> +	388d0eedbfc3864bbbf7ad7f965064d99cac5aaa
This one could use comments.
So, is that a SVN commit, or?

2024-07-02 16:59 UTC, TomJo2000 commented on packages/perl/build.sh
> +	http://www.cpan.org/src/5.0/perl-${TERMUX_PKG_VERSION}.tar.gz
```suggestion
	http://www.cpan.org/src/5.0/perl-${TERMUX_PKG_VERSION[0]}.tar.gz
```

2024-07-02 16:59 UTC, TomJo2000 commented on packages/perl/build.sh
> +#	https://github.com/arsv/perl-cross/releases/download/${TERMUX_PKG_VERSION[1]}/perl-cross-${TERMUX_PKG_VERSION[1]}.tar.gz
```suggestion

```

2024-07-02 16:59 UTC, TomJo2000 commented on packages/rw/build.sh
> +TERMUX_PKG_SRCURL=https://github.com/jridgewell/rw/archive/c13c24e011ef5a79ea60bc51bb0d3fa930326146.tar.gz
> [!IMPORTANT]
> Why are we hardcoding the commit here?
> I think you can drop this one and I'll fix it in a separate PR.

2024-07-02 16:59 UTC, TomJo2000 commented on packages/softether-vpn/build.sh
> +	https://github.com/SoftEtherVPN/SoftEtherVPN/releases/download/${TERMUX_PKG_VERSION}/SoftEtherVPN-${TERMUX_PKG_VERSION}.tar.xz
```suggestion
	https://github.com/SoftEtherVPN/SoftEtherVPN/releases/download/${TERMUX_PKG_VERSION[0]}/SoftEtherVPN-${TERMUX_PKG_VERSION[0]}.tar.xz
```

2024-07-02 16:59 UTC, TomJo2000 commented on packages/texinfo/build.sh
These parts of the custom auto_update function are being superseded by the standard behavior of `termux_pkg_upgrade_version`?

2024-07-02 16:59 UTC, TomJo2000 commented on packages/unar/build.sh
> +	https://github.com/MacPaw/XADMaster/archive/v${TERMUX_PKG_VERSION}/XADMaster-${TERMUX_PKG_VERSION}.tar.gz
You know the drill.
```suggestion
	https://github.com/MacPaw/XADMaster/archive/v${TERMUX_PKG_VERSION[0]}/XADMaster-${TERMUX_PKG_VERSION[0]}.tar.gz
```

2024-07-02 16:59 UTC, TomJo2000 commented on scripts/bin/update-checksum
I'll review this again in a separate pass later.
But I think we've covered everything in here already.

2024-07-02 16:59 UTC, TomJo2000 commented on x11-packages/tigervnc/build.sh
> +	https://github.com/TigerVNC/tigervnc/archive/v${TERMUX_PKG_VERSION}.tar.gz
```suggestion
	https://github.com/TigerVNC/tigervnc/archive/v${TERMUX_PKG_VERSION[0]}.tar.gz
```

2024-07-02 16:59 UTC, TomJo2000 commented on packages/ldc/build.sh
> +	https://github.com/ldc-developers/ldc/releases/download/v${TERMUX_PKG_VERSION}/ldc-${TERMUX_PKG_VERSION}-src.tar.gz
```suggestion
	https://github.com/ldc-developers/ldc/releases/download/v${TERMUX_PKG_VERSION[0]}/ldc-${TERMUX_PKG_VERSION[0]}-src.tar.gz
```

2024-07-02 22:56 UTC, tqfx commented
For multiple versions, I think it can be managed in the following form.

```sh
TERMUX_PKG_VERSION=""
_OTHER_VERSION=""
```

Then rewrite `termux_pkg_auto_update` in `build.sh`. This way auto-update works and `_OTHER_VERSION` is easily modified by `sed`.

2024-07-02 23:29 UTC, TomJo2000 commented
> For multiple versions, I think it can be managed in the following form.
> 
> ```shell
> TERMUX_PKG_VERSION=""
> _OTHER_VERSION=""
> ```
> 
> Then rewrite `termux_pkg_auto_update` in `build.sh`. This way auto-update works and `_OTHER_VERSION` is easily modified by `sed`.

We could use associative arrays.
```bash
declare -A TERMUX_PKG_VERSION=(
    [foo]='0.1.2'
    [bar]='6.4.12'
    [baz]='11.0-beta7'
)
```
But that wouldn't really be any less complicated.
I think an indexed array approach can work just fine,
but I'll need to do some testing to work something out.

2024-07-03 00:52 UTC, tqfx commented
Associative arrays do not work with `termux_pkg_upgrade_version`.

2024-07-03 00:55 UTC, TomJo2000 commented
> Associative arrays do not work with `termux_pkg_upgrade_version`.

Would be extra work to make them.
I'll see about getting indexed arrays working for the version tomorrow.

2024-07-03 02:29 UTC, truboxl commented
This PR is about update-checksum and interaction with build.sh. Anything else (changing termux_pkg_auto_update) is just adding noise at this point.

2024-07-07 15:09 UTC, truboxl approved these changes

2024-07-07 17:32 UTC, licy183 commented on x11-packages/virglrenderer-android/build.sh
> +TERMUX_PKG_AUTO_UPDATE=true
IMO `virglrender-android` should not be auto-updated. It needs tests before updating.

2024-07-07 21:28 UTC, TomJo2000 approved these changes

2024-07-10 13:22 UTC, licy183 approved these changes

2024-07-11 02:37 UTC, merged