fixing issue #20818 . upgrade gnucobol upstream and the local patches to allow usage of indexed files by libdb.
termux/termux-packages pull request #20961
Opened 2024-07-26 14:04 UTC by alexbodn

the patches to packages/gnucobol solve the problem in issue #20818  entirely, while also upgrading upstream gnucobol.

however, i'm about to ask upstream to adopt one hefty patch file, so that the package will be termux related only.

does my PR include commits out of packages/gnucobol they may be safely discarded as unrelated.

2024-07-26 15:51 UTC, alexbodn commented
i know the patch seems a mess, since the commits are my progress with building and checking the package.
here is one file patch that diffs end - start without any back and forth, or other directories.
[gnucobol.patch](https://github.com/user-attachments/files/16393931/gnucobol.patch)

2024-07-26 16:53 UTC, GitMensch commented
These are too many commits. Can you please squash them into two (one for the update, the other for bdb compatibility and use)?

2024-07-26 16:55 UTC, GitMensch commented on packages/gnucobol/build.sh
> +TERMUX_PKG_REVISION=4
If you increase the version then revision is to be set to 0 or 1 (please check the docs)

2024-07-26 16:58 UTC, GitMensch reviewed
Packages libdb should be part of a separate PR, no?

2024-07-27 10:27 UTC, alexbodn commented
> Packages libdb should be part of a separate PR, no?

sure, i didn't know how to proceed, so i have initialy pushed all my commits during this period.
to correct this, i have attached to my other comment the diff of packages/gnucobol only from my first checkout to my last commit.
btw, @GitMensch , my upstream.patch doesn't have much to do with termux, has some missed missing includes and could help with any cross compilation, so i'd encourage you to apply to your distro. configure is autogenerated, but it's needed for now already.

2024-07-27 10:37 UTC, alexbodn commented
> These are too many commits. Can you please squash them into two (one for the update, the other for bdb compatibility and use)?

sure, the workflow is triggered by commits, so all my trials had to be commited.
i've also sent a one patch from start to end.

[here it is](https://github.com/termux/termux-packages/pull/20961#issuecomment-2253042099)

> gnucobol.patch

2024-07-27 11:49 UTC, TomJo2000 commented
> sure, the workflow is triggered by commits, so all my trials had to be commited. i've also sent a one patch from start to end.

The workflows are also dispatched when force pushing to a PR branch.
I recommend you familiarize yourself with the `git commit --amend`, `git rebase -i` and `git push --force-with-lease=` commands.

2024-07-27 12:02 UTC, TomJo2000 requested changes
Completely unmergable in its current state.
Barely reviewable as is too.

2024-07-27 14:01 UTC, alexbodn commented on scripts/lint-packages.sh
> +##					pkg_lint_error=true
this was for another package. this one does pass.
could you take a lokk a my gnucobol.patch file attached to a comment above?
it doesn't contain other directories, nor back and forth trials.

2024-07-27 14:03 UTC, alexbodn commented on packages/libdb6/build.sh
> +TERMUX_PKG_LICENSE=Sleepycat
it's not mine. probably came when i synced my fork.

2024-07-27 14:04 UTC, alexbodn commented on packages/libdb6/build.sh
> +TERMUX_PKG_BLACKLISTED_ARCHES="arm, i686, x86_64"
sure.
first, it's another package i tried to build.
it's build took a lot of time, and i could only try on aarch64.

2024-07-27 14:08 UTC, alexbodn commented on packages/libdb6/build.sh
> +TERMUX_PKG_DESCRIPTION="The Berkeley DB embedded database system (library) last non AGPL"
libdb6 is not the issue in this PR.
1. libdb 6.0.19 was the last libdb that is not AGPL.
2. v6 had more features dropped in very 18.1.40, like sql and client-server interfaces.
3. debian also prefer v5, even older.

2024-07-27 14:21 UTC, alexbodn commented on packages/gnucobol/upstream.patch
i'd rather look at gnucobol.patch instead. do Ctrl-F here. it contains only changes to packages/gnucobol.

the PR itself mirrors all my commits to my termux-packages fork during my work on gnucobol. as the CI workflow would only work on commits, i had to commit all my trials until i got the problem fixed. a big thank goes to github for all these resources.

the problem my patch came to solve was with the upstream configure script that wouldn't work correctly when cross compiling.
most of my patch, the file `packages/gnucobol/upstream.patch` is directed to the upstream developers. i will delete it here once they apply it.
however it's here to make gnucobol run correctly already, based on their current official released archive.

2024-07-27 14:26 UTC, alexbodn commented on packages/libdb6/build.sh
> +TERMUX_PKG_LICENSE=Sleepycat
Sleepycat was on the list of licenses on termux-packages, but indeed lint didn't pass.

2024-07-27 15:48 UTC, GitMensch commented on packages/gnucobol/upstream.patch
I'll have a look at this patch (and guess most things area already solved in the current dev snapshot for GnuCOBOL 3.3, but the final release will take some months)

2024-07-28 09:04 UTC, alexbodn commented
the problems in this PR challenged me to try a better way to wrap my changes.

thank you everybody.

i'm closing this PR and have submitted another [at](https://github.com/termux/termux-packages/pull/20968).

2024-07-28 09:04 UTC, closed without merging

2024-07-28 10:10 UTC, GitMensch commented
Can you please create another PR for BDB?