fix(main/telegram-bot-api): Switch to tag version control
termux/termux-packages pull request #21067
Opened 2024-08-07 07:49 UTC by Sarisan

2024-08-07 07:54 UTC, Sarisan commented
Wasn't supposed to be opened now.

2024-08-08 11:23 UTC, licy183 requested changes

2024-08-08 11:23 UTC, licy183 commented on packages/telegram-bot-api/build.sh
> +TERMUX_PKG_VERSION="7.8"
Epoch should be bumped to 1 as `7.8` < `20240730`

```suggestion
TERMUX_PKG_VERSION="1:7.8"
```

2024-08-08 13:21 UTC, Biswa96 commented
The change is using a fork of the actual repository. I am not sure if that should be done.

2024-08-08 13:35 UTC, Sarisan commented
> The change is using a fork of the actual repository. I am not sure if that should be done.

I don't see any other way to implement auto updates for this packages, other than if there were tags, it would still require manipulations with git and submodule. I can actually try to ask developer to tag releases, but I doubt they will.

2024-08-08 13:39 UTC, Biswa96 commented
Not all packages can be auto-updated. I would recommend maintaining the current version type if upstream does not have proper tags.

2024-08-08 13:49 UTC, Sarisan commented
I will wait for developer response, closing this till then.
https://github.com/tdlib/telegram-bot-api/issues/623

2024-08-08 13:49 UTC, closed without merging