chore(main/bionic-host): fix downloading ubuntu packages, disable undefined symbols checking, disable `repo` SHA256 verification
termux/termux-packages pull request #21825
Opened 2024-10-15 22:05 UTC by twaik

Replaces #21095

2024-10-15 23:26 UTC, twaik commented
@Grimler91 ping because you authored #21095.

2024-10-15 23:27 UTC, twaik commented
Last run is successful (https://github.com/termux/termux-packages/actions/runs/11355611298), I commited revbump to avoid problems after squashing and merging to master.

2024-10-16 02:22 UTC, robertkirkman commented
Thank you! I was also building this and when I apply your PR it builds successfully.

> jammy is last known distro which contains `libncurses.so.5` in packages

I'm not sure if maybe you meant the last known Ubuntu distro, but technically, Debian 12 released at a date later than Ubuntu 22.04 and it contains that package.

That means that when I apply this change to your PR it still builds, but maybe there's a specific reason it has to be the Ubuntu 22.04 version that I don't know about.

One possible comment in favor of this suggestion I could make is that, in my experience, https://cdn-fastly.deb.debian.org/ is usually a significantly more reliable mirror than alternatives. However maybe that does not matter at all anymore since you have implemented a loop to retry on failure.

```diff
--- a/packages/bionic-host/build.sh
+++ b/packages/bionic-host/build.sh
@@ -11,8 +11,8 @@ TERMUX_PKG_SKIP_SRC_EXTRACT=true
 
 # Function to obtain the .deb URL
 obtain_deb_url() {
-	# jammy is last known distro which contains `libncurses.so.5` in packages
-	local url="https://packages.ubuntu.com/jammy/amd64/$1/download"
+	# bookworm is last known distro which contains `libncurses.so.5` in packages
+	local url="https://packages.debian.org/bookworm/amd64/$1/download"
 	local retries=5
 	local wait=5
 	local attempt
@@ -22,7 +22,8 @@ obtain_deb_url() {
 		local PAGE="$(curl -s "$url")"
 		>&2 echo page
 		>&2 echo "$PAGE"
-		if deb_url=$(echo "$PAGE" | grep -Eo 'http://.*\.deb' | head -n 1); then
+		if deb_url=$(echo "$PAGE" | grep -Eo 'http://http.us.debian.org/.*amd64.deb' | head -n 1 | \
+		sed -e 's/http:\/\/http.us/https:\/\/cdn-fastly.deb/'); then
 			if [[ -n "$deb_url" ]]; then
 				echo "$deb_url"
 				return 0
@@ -65,7 +66,7 @@ termux_step_get_source() {
 
 		mkdir -p ${TERMUX_PKG_TMPDIR}/${URL##*/}
 		ar x ${TERMUX_PKG_CACHEDIR}/${URL##*/} --output=${TERMUX_PKG_TMPDIR}/${URL##*/}
-		tar xf ${TERMUX_PKG_TMPDIR}/${URL##*/}/data.tar.zst -C ${TERMUX_PKG_SRCDIR}/prefix
+		tar xf ${TERMUX_PKG_TMPDIR}/${URL##*/}/data.tar.xz -C ${TERMUX_PKG_SRCDIR}/prefix
 	done
 
 	termux_download https://storage.googleapis.com/git-repo-downloads/repo ${TERMUX_PKG_CACHEDIR}/repo SKIP_CHECKSUM
```

2024-10-16 08:38 UTC, twaik commented
> Debian 12 released at a date later than Ubuntu 22.04 and it contains that package.

Github CI uses ubuntu imqges so I prefer to use Ubuntu's repos for this purpose, but good catch. Thank you.

2024-10-16 09:53 UTC, truboxl requested changes

2024-10-16 13:10 UTC, twaik commented on packages/bionic-host/build.sh
> +termux_step_massage() {
Done

2024-10-16 13:24 UTC, truboxl approved these changes

2024-10-16 13:25 UTC, twaik commented
> Something about needing to deal with Google's source management just feels icky to me.

I can do nothing with it, it is the way AOSP ROM is being built. Sorry.

2024-10-16 13:26 UTC, merged