fix(main/xmlto): Don't hardcode build-machine paths to tools
termux/termux-packages pull request #21912
Opened 2024-10-20 22:40 UTC by SamB

Now it actually works on my phone

2024-10-20 22:50 UTC, TomJo2000 requested changes

2024-10-20 22:50 UTC, TomJo2000 commented on packages/xmlto/build.sh
> +TERMUX_PKG_EXTRA_CONFIGURE_ARGS="XMLTO_BASH_PATH=/bin/bash MKTEMP=mktemp FIND=find GETOPT=getopt PAPER_CONF=paperconf LOCALE=locale XMLLINT=xmllint XSLTPROC=xsltproc DBLATEX=dblatex FOP=fop XMLTEX=xm
The extra configure args should be one per line if there's that many.
```suggestion
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
	XMLTO_BASH_PATH=/bin/bash
	MKTEMP=mktemp
	FIND=find
	GETOPT=getopt
	PAPER_CONF=paperconf
	LOCALE=locale
	XMLLINT=xmllint
	XSLTPROC=xsltproc
	DBLATEX=dblatex
	FOP=fop
	XMLTEX=xmltex
	PDFXMLTEX=pdfxmltex
	LYNX=lynx
	LINKS=elinks
	W3M=w3m
	TAIL=tail
	GREP=grep
	SED=sed
	CP=cp
	ZIP=zip
"
```
Also the path for bash should be:
```bash
	XMLTO_BASH_PATH=${TERMUX_PREFIX}/bin/bash
```
The rest of the program assignments are probably unnecessary.

2024-10-20 22:50 UTC, TomJo2000 commented on packages/xmlto/build.sh
> +	sed -e 's/^AC_PATH_PROG/AC_CHECK_PROG/' -i~ configure.ac
This should probably be a patch instead.

2024-10-20 22:52 UTC, twaik requested changes

2024-10-20 22:52 UTC, twaik commented on packages/xmlto/build.sh
> +TERMUX_PKG_EXTRA_CONFIGURE_ARGS="XMLTO_BASH_PATH=/bin/bash MKTEMP=mktemp FIND=find GETOPT=getopt PAPER_CONF=paperconf LOCALE=locale XMLLINT=xmllint XSLTPROC=xsltproc DBLATEX=dblatex FOP=fop XMLTEX=xm
Please, format it as a multiline string like it is done in https://github.com/termux/termux-packages/blob/7cd73dd3538c632c3d81492a798c760c82134f40/packages/gnupg/build.sh#L13-L17

2024-10-20 23:13 UTC, TomJo2000 commented on packages/xmlto/build.sh
> +	sed -e 's/^AC_PATH_PROG/AC_CHECK_PROG/' -i~ configure.ac
Nvm I changed my mind on that.
But I'm not sure why we're using `-i~`
https://github.com/termux/termux-packages/blob/7cd73dd3538c632c3d81492a798c760c82134f40/packages/groff/build.sh#L21-L23
Just `-i` seems to be more standard when `sed` is used in a build script to make changes.

2024-10-21 20:52 UTC, twaik approved these changes

2024-10-21 20:53 UTC, twaik commented
Will be merged in 72 hours if no one minds or after it gets 2+ more approves.

2024-10-24 22:54 UTC, merged