Capnp
termux/termux-packages pull request #5813
Opened 2020-09-16 17:28 UTC by ihsakashi

2020-09-16 19:43 UTC, xeffyr requested changes

2020-09-16 19:43 UTC, xeffyr commented on packages/capnproto/build.sh
> +TERMUX_PKG_DESCRIPTION="Cap'n Proto tool and library"
Use normal description here. We all know that package contains cap'n proto stuff, but what is it?
```
Data interchange format and capability-based RPC system.
```

2020-09-16 19:43 UTC, xeffyr commented on packages/capnproto/build.sh
> +    ./configure \
Don't run ./configure on your own, especially if you don't know the correct arguments for cross-compilation.

`termux_step_configure` should be overridden only in special cases, e.g. when project doesn't use GNU autotools.

2020-09-16 21:43 UTC, ihsakashi commented
Only one thing stopping it building. When makefile runs `test_capnpc_middleman` in the docker, it fails with this:
`./capnp: line 117: /home/builder/.termux-build/capnproto/src/.libs/capnp: cannot execute binary file: Exec format error`.

It works fine building on device. I will submit patch removing test, is that fine?

2020-09-16 22:26 UTC, xeffyr commented
> When makefile runs test_capnpc_middleman in the docker, it fails with this

Tests can't be executed. That's known issue and we are just skipping them.

2020-09-17 01:42 UTC, ihsakashi commented
So I've removed the tests in Makefile, but i keep getting linker errors when installing. Everytime `test_capnpc_middleman` where the exec error is runs, it outputs dependencies I think and I can't get any further than that. 

https://github.com/capnproto/capnproto/blob/dec294c0de3dda355df11e5b2a69bea78f417516/c%2B%2B/Makefile.am#L429

Can you check it out? I'm stuck :(

2020-09-25 14:01 UTC, xeffyr commented
I have switched build.sh to force use cmake as project supports it. Tests seems to be automatically disabled because can't be done when cross-compiling.

2020-09-25 14:27 UTC, merged