Sysbench
termux/termux-packages pull request #5825
Opened 2020-09-18 13:51 UTC by ifurther

#4767

2020-09-25 13:27 UTC, xeffyr requested changes
Do you have any proof that `sysbench` works properly in Termux? Last time I tried it, I have got ridiculous results (Termux is >100 times faster than 8 core Google Cloud server???LOL).

2020-09-25 13:27 UTC, xeffyr commented on packages/sysbench/build.sh
> +TERMUX_PKG_DEPENDS="luajit, libluajit, openssl, postgresql, libaio, concurrencykit"
I have built sysbench without ANY of these (well, `openssl` was already installed).

concurrencykit also requires patching.

2020-09-29 19:18 UTC, AdrMXR approved these changes

2020-10-01 14:39 UTC, xeffyr commented
Everything that is required:
```
./autogen.sh && ./configure --without-pgsql --without-mysql
make
```

Also will need a patch to implement `pthread_cancel` - through atomic flags. Do not replace it with `pthread_kill`.

Closing this for now as not acceptable.

2020-10-01 14:39 UTC, closed without merging