add eja micro web server
termux/termux-packages pull request #6051
Opened 2020-11-20 15:30 UTC by ubaldus

Adding package **eja** from debian _web_ subsection.

2020-11-20 15:39 UTC, Grimler91 requested changes
Hi, see comments

2020-11-20 15:39 UTC, Grimler91 commented on packages/eja/build.sh
> +
Please delete the header

2020-11-20 15:39 UTC, Grimler91 commented on packages/eja/build.sh
> +TERMUX_PKG_HOMEPAGE=http://eja.it
use https instead of http, since https://eja.it seem to exist

2020-11-20 15:39 UTC, Grimler91 commented on packages/eja/build.sh
> +TERMUX_PKG_EXTRA_MAKE_ARGS="DESTDIR=$TERMUX_PREFIX prefix=/"
Why setting `DESTDIR=$TERMUX_PREFIX` and `prefix=/`? I think build should work if you remove this line

2020-11-20 15:56 UTC, ubaldus commented
ok, thank you for checking.

2020-11-20 16:23 UTC, ubaldus commented
the extra make argument is needed to allow correct installation of the manual.

2020-11-20 19:14 UTC, Grimler91 commented
> the extra make argument is needed to allow correct installation of the manual.

Alright, so it is because prefix, [as given as environmental var](https://github.com/termux/termux-packages/blob/273a6ff7a1aa68c9bdd5f30693ec40940b5b559c/scripts/build/termux_step_setup_variables.sh#L89), [is overwritten in the Makefile](https://github.com/eja/eja/blob/52408581889cd2ec4414c1bd7da0212a51752fcc/Makefile#L1). 

You don't need to set DESTDIR, `TERMUX_PKG_EXTRA_MAKE_ARGS="prefix=$TERMUX_PREFIX"` is enough. (Another possibility would be update the Makefile to have `prefix ?= /usr/local`, then `TERMUX_PKG_EXTRA_CONFIGURE_ARGS` would not have to be set).

2020-11-22 18:36 UTC, xeffyr commented
As it seems everything installed to correct place, I'll merging this.
```
drwx------ builder/builder   0 2020-11-20 18:31 ./data/data/com.termux/files/usr/
drwx------ builder/builder   0 2020-11-20 18:31 ./data/data/com.termux/files/usr/bin/
-rwx------ builder/builder 414472 2020-11-20 18:31 ./data/data/com.termux/files/usr/bin/eja
drwx------ builder/builder      0 2020-11-20 18:31 ./data/data/com.termux/files/usr/share/
drwx------ builder/builder      0 2020-11-20 18:31 ./data/data/com.termux/files/usr/share/doc/
drwx------ builder/builder      0 2020-11-20 18:31 ./data/data/com.termux/files/usr/share/doc/eja/
lrwxrwxrwx builder/builder      0 2020-11-20 18:31 ./data/data/com.termux/files/usr/share/doc/eja/LICENSE -> ../../LICENSES/GPL-3.0.txt
drwx------ builder/builder      0 2020-11-20 18:31 ./data/data/com.termux/files/usr/share/man/
drwx------ builder/builder      0 2020-11-20 18:31 ./data/data/com.termux/files/usr/share/man/man1/
-rwx------ builder/builder    858 2020-11-20 18:31 ./data/data/com.termux/files/usr/share/man/man1/eja.1.gz
```

All further improvements can be done later, if necessary.

2020-11-22 18:37 UTC, merged