Add package: gradle
termux/termux-packages pull request #7227
Opened 2021-08-01 10:40 UTC by suhan-paradkar

Will be a draft until someone confirms that it works without any problem

2021-08-01 10:52 UTC, xeffyr requested changes

2021-08-01 10:52 UTC, xeffyr commented on packages/gradle/build.sh
> +TERMUX_PKG_DESCRIPTION="Adaptable, fast automation for all"
`Powerful build system for the JVM`

2021-08-01 11:54 UTC, suhan-paradkar commented on packages/gradle/build.sh
> +TERMUX_PKG_DESCRIPTION="Adaptable, fast automation for all"
Done

2021-08-02 11:45 UTC, xeffyr commented
It doesn't work. When building even simple project, it fails with `Unsupported class file major version 61`.

2021-08-02 11:50 UTC, suhan-paradkar commented
Well.. looks like gradle doesn't support openJDK 17 yet...
https://docs.gradle.org/current/userguide/compatibility.html#compatibility

2021-08-02 15:36 UTC, agnostic-apollo commented
Try [`7.2-rc-1`](https://services.gradle.org/distributions/) as per https://github.com/gradle/gradle/issues/16857#issuecomment-881635400

2021-08-03 00:46 UTC, suhan-paradkar commented
Lemme try

2021-08-03 01:59 UTC, suhan-paradkar commented
@xeffyr should I open a PR here or in unstable-repo for gradle-nightly (v7.2-rc-1 as per @agnostic-apollo ) ??

2021-08-03 02:09 UTC, thunder-coding commented
unstable-packages would be better until it is tested to be working. (Vote here instead of commenting)
👍  for upvote
👎  for downvote

2021-08-03 02:13 UTC, agnostic-apollo commented
Well, technically all this stuff with jdk, kotlin, gradle, etc is pretty nightly/unstable at this point considering the issues and only basic testing having being done yet. But we can test without merging with master too.

2021-08-03 02:21 UTC, suhan-paradkar commented
@agnostic-apollo so should I open a new PR or continue with this(this PR will be reopened)??

2021-08-03 02:24 UTC, agnostic-apollo commented
Send the changes here I guess, will see if build even succeeds and gradle actually works or not. Decision to move it to unstable repo can be made after that, no point in doing that now if gradle doesn't even work.

2021-08-03 02:25 UTC, suhan-paradkar commented
I have already made changes see `2086ffb`

2021-08-03 04:43 UTC, suhan-paradkar commented
Well.. it builds... Need to check if it works...

2021-08-03 12:02 UTC, suhan-paradkar commented
Well.. It works... I can confirm it...

I could test jadx

![Screenshot_2021-08-03-17-13-39-18.jpg](https://user-images.githubusercontent.com/76830230/128012000-490bccb2-dad6-430e-9af9-93e7aea44f0b.jpg)![Screenshot_2021-08-03-17-20-28-37.jpg](https://user-images.githubusercontent.com/76830230/128012029-8236fe21-d5c5-413f-ac43-416c878ac2d9.jpg)![Screenshot_2021-08-03-17-20-37-58.jpg](https://user-images.githubusercontent.com/76830230/128012054-ca488201-39c6-43d8-8e6c-29511ea7b021.jpg)

2021-08-04 22:43 UTC, agnostic-apollo commented
Welcome and apologies for the following *journey*! ;)

So TLDR is that `gradle` is working with `openjdk-17`. I have managed to compile `termux-app` and `termux-tasker` with them on my LG G5 Android `7.0`, `aarch64`. But was hell to do it.



<details>
<summary>There is one exception that `gradle` with `--debug` flag does show when running tasks that I noticed but it still worked.</summary>

```
net.rubygrapefruit.platform.NativeIntegrationLinkageException: Native library 'libnative-platform.so' could not be loaded for Linux aarch64.
	at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:61)
	at net.rubygrapefruit.platform.Native.init(Native.java:56)
	at org.gradle.internal.nativeintegration.services.NativeServices.initializeNativeIntegrations(NativeServices.java:170)
	at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:155)
	at org.gradle.internal.nativeintegration.services.NativeServices.initializeOnClient(NativeServices.java:135)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:42)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:240)
	at org.gradle.launcher.Main.doAction(Main.java:35)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
Caused by: java.lang.UnsatisfiedLinkError: /data/data/com.termux/files/home/termux_img/.gradle/native/e1d6ef7f7dcc3fd88c89a11ec53ec762bb8ba0a96d01ffa2cd45eb1d1d8dd5c5/linux-aarch64/libnative-platform.so: dlopen failed: library "libstdc++.so.6" not found
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:751)
	at java.base/java.lang.System.load(System.java:1912)
	at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:51)
	... 18 more
```
</details>
&nbsp;&nbsp;

I am not well versed in the `gradle` and android `sdk`/`apk` build systems, so some issues will need more research. Anyways, firstly, as already mentioned, `gradle` does work with `jdk-17`, but android `gradle` plugin is **not** officially supported and has issues. It will fail with `Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @6a45f906` while compiling `termux-*` and will likely get triggered for other apps too. Similar issue reported at https://github.com/gradle/gradle/issues/17152#issuecomment-839607617. As per [this](https://issuetracker.google.com/issues/191390856), even `jdk-16` is not supported by android `gradle` plugin/studio, at least was not in June. The [official docs](https://developer.android.com/studio/releases/gradle-plugin) only mention minimum version `11`, but not max. However, that issue is solvable by adding `--add-opens=java.base/java.io=ALL-UNNAMED` to `org.gradle.jvmargs` in root level `gradle.properties`. This is due to newer restrictions in `jdk-17` of accessing internal APIs with reflection, so that error may get triggered for other classes as well and each will have to be opened separately. Check https://www.infoq.com/news/2021/06/internals-encapsulated-jdk17/ for details.

So lets begin setup.

### Set Environmental Variables

First we need to set `ANDROID_SDK_ROOT`, `JAVA_HOME` and update `PATH`. Add following to `~/.bashrc`. You will need to `source` it with `source ~/.bashrc` or start a new termux session for changes to take effect. You will also need to stop the `gradle` daemon with `gradle --stop`, since it will be using old values if its already running.

```
export ANDROID_SDK_ROOT="$HOME/Android/sdk"
export PATH="$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin"
export JAVA_HOME=/data/data/com.termux/files/usr/opt/openjdk
```

So `~/Android/sdk` directory will be where we store android `sdk` related files. The `~/.gradle` directory is used by `gradle` for storing its own files like dependencies in `caches`, etc. 

### Download `cmdline-tools`

We need the tools provided by [`cmdline-tools`](https://developer.android.com/studio/command-line#tools-sdk). You can also download it directly from https://developer.android.com/studio#command-tools. Note that we added its extraction path to `PATH` in `.bashrc`, which is required so that it can be executed from *anywhere*, without referring to its path. These tools are scripts and architecture is not an issue. We need `sdkmanager` from it to install other `sdk` packages, like the ones you see in Android Studio SDK manager.

```
curl -L https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -o commandlinetools-linux-7583922_latest.zip
mkdir -p ~/Android/sdk/cmdline-tools
unzip commandlinetools-linux-7583922_latest.zip -d ~/Android/sdk/cmdline-tools
mv ~/Android/sdk/cmdline-tools/cmdline-tools ~/Android/sdk/cmdline-tools/latest
```

### Accept Android SDK Licenses

You will get errors like `Failed to install the following Android SDK packages as some licences have not been accepted.` if you try to install packages with `sdkmanager`. So run `yes | sdkmanager --licenses` so that google owns your soul (if it doesn't already).


### Install Android Platforms

Since we are only compiling `termux-app` and `termux-tasker`, we would mainly only need Android sdk `28`, `29` and `30` now and near future.

```
yes | sdkmanager "platforms;android-28"
yes | sdkmanager "platforms;android-29"
yes | sdkmanager "platforms;android-30"
```

### Install Android Build And Platform Tools

Now, if at this point if you try to run a `gradle` task for `termux-tasker`, hoping it will download the [`build-tools`](https://developer.android.com/studio/command-line#tools-build) automatically for you, then you are right, it will, well, it will try to, but it will fail with `Failed to install the following SDK components: build-tools;29.0.2`. Note that `termux-tasker` does not set `buildToolsVersion` in [`app/build.gradle`](https://github.com/termux/termux-tasker/blob/v0.5/app/build.gradle) and the android `gradle` plugin will [automatically choose the minimum required version since `3.0.0`](https://developer.android.com/studio/releases/gradle-plugin#3-0-0). Since `termux-tasker` uses [`com.android.tools.build:gradle:4.1.1`](https://github.com/termux/termux-tasker/blob/v0.5/build.gradle#L8),  [`build-tools;29.0.2` would be chosen](https://developer.android.com/studio/releases/gradle-plugin#4-1-0). The `termux-app` uses [`com.android.tools.build:gradle:4.2.1`](https://github.com/termux/termux-app/blob/v0.117/build.gradle#L7), so [`build-tools;30.0.2` would be chosen](https://developer.android.com/studio/releases/gradle-plugin#4-2-0).

So the solution would have be [...]

2021-08-05 04:02 UTC, masterjavaofficial commented
![Screenshot_2021-08-05-09-56-12-502_com android chrome](https://user-images.githubusercontent.com/78401450/128288651-6b953b69-6e7b-4ea7-b2d5-5de501b600d0.jpg)
These have been one of my dreams for years!!
When did you do all these? I've been trying the same for the last 3 months, using https://github.com/Lzhiyong/'s OpenJDK and Android SDK + NDK in Termux's shell!! Hope it gets available in near future!! ☺️

Although the packages are big, which seems not get accepted as bigger than 150 even 200 MBs, but those are most demanded.. Thanks for this pull request!! ❤️

2021-08-05 05:18 UTC, Hax4us commented
According to https://github.com/jrodbx/agp-sources/blob/2b16dd9e08744d6e4f011fa5d0c550530c6a2c0e/4.2.0-alpha12/com.android.tools.build/gradle/com/android/build/gradle/internal/res/Aapt2FromMaven.kt#L83 , we can specify custom local aapt2 like this (gradle.properties)

`android.aapt2FromMavenOverride=/path/to/aapt2`

2021-08-05 07:42 UTC, agnostic-apollo commented
> According to https://github.com/jrodbx/agp-sources/blob/2b16dd9e08744d6e4f011fa5d0c550530c6a2c0e/4.2.0-alpha12/com.android.tools.build/gradle/com/android/build/gradle/internal/res/Aapt2FromMaven.kt#L83 , we can specify custom local aapt2 like this (**gradle.properties**)
> 
> `android.aapt2FromMavenOverride=/path/to/aapt2`

Thanks, it is working: `WARNING:: The option setting 'android.aapt2FromMavenOverride=/data/data/com.termux/files/home/termux_img/Android/sdk/build-tools/latest/aapt2' is experimental.`.

Moreover, as per [this](https://stackoverflow.com/a/54618642), we can export a custom repo url for `sdkmanager` with `SDK_TEST_BASE_URL`, although seems to have [caching issues](https://stackoverflow.com/a/62569479). At least should make things easier if we host a custom repo for `build-tools` and `platform-tools`.

2021-08-05 09:02 UTC, agnostic-apollo commented
@masterjavaofficial

>These have been one of my dreams for years!!
>When did you do all these?

The ones in the picture are for the future, they are not done yet. The building of termux-app with `openjdk-17` and `gradle` ([this pull request artifact](https://github.com/termux/termux-packages/pull/7227/checks?check_run_id=3226851250)) package was done in last 2 days.

>I've been trying the same for the last 3 months, using https://github.com/Lzhiyong/'s OpenJDK and Android SDK + NDK in >Termux's shell!! Hope it gets available in near future!! relaxed

Didn't instructions at https://github.com/Lzhiyong/termux-ndk/tree/master/build-app work?

Note that Lzhiyong/* releases are only for `aarch64` so don't expect building for other architectures currently.

2021-08-05 09:06 UTC, agnostic-apollo commented
I don't see any issues with the pull request currently, @xeffyr any changes before its merged?

2021-08-05 10:22 UTC, suhan-paradkar commented
Since Lzhiyong/*  packages have their patches out open I guess it would be easier to port them tho.. won't it @agnostic-apollo ?

2021-08-05 12:00 UTC, agnostic-apollo commented
> Since Lzhiyong/* packages have their patches out open I guess it would be easier to port them tho.. won't it @agnostic-apollo ?

For NDK can't really say without actually trying to port. Considering OP says it builds in proot, so should be build-able in docker as well. Some build instructions are commented out as well as pseudo code, but a script to automatically build it should be possible. Not sure exactly what issues may arise, NDK is huge. Also patches are version dependent and there are different components that need building.

https://github.com/Lzhiyong/termux-ndk#issues

>each NDK version has a lot of changes, direct compilation will fail, the build script are not generic, so please solve the error yourself.

`build-tools` would probably be easier.

2021-08-05 13:22 UTC, suhan-paradkar commented
Also.. I don't think it would compile easily on 32-bit platforms tho....

2021-08-05 14:24 UTC, Yisus7u7 commented
> Además ... aunque no creo que se compile fácilmente en plataformas de 32 bits ...

Just that I was going to ask, I'm unfortunately a 32-bit user

2021-08-05 16:10 UTC, agnostic-apollo commented
>Also.. I don't think it would compile easily on 32-bit platforms tho....

NDK is not officially supported on `arm32`, `arm64` or linux `x86`. Its working on `arm64` with hacks, they may or may not be possible for `arm32` in current versions. No specific need for on device builds of NDK itself.

https://groups.google.com/g/android-ndk/c/tcxcRWsBINQ
https://developer.android.com/ndk/guides/other_build_systems
https://github.com/Lzhiyong/termux-ndk/blob/master/patches/ndk-build.patch

2021-08-05 16:41 UTC, xeffyr approved these changes

2021-08-05 16:41 UTC, merged

2021-08-05 18:28 UTC, Yisus7u7 commented
Ok, I'll look forward to java in 32-bit

2023-03-27 15:05 UTC, Faory212 reviewed
Co

2024-03-12 14:12 UTC, Git2020104 commented
But I get this error message when extracting Lzhiyong/sdk-tools

_tar: This does not look like a tar archive        xz: (stdin): File format not recognized           tar: Child returned status 1                      tar: Error is not recoverable: exiting now_

Why?? Yet i have followed all steps well upto this point.

2024-03-12 14:15 UTC, thunder-coding commented
> But I get this error message when extracting Lzhiyong/sdk-tools
> 
> _tar: This does not look like a tar archive xz: (stdin): File format not recognized tar: Child returned status 1 tar: Error is not recoverable: exiting now_
> 
> Why?? Yet i have followed all steps well upto this point.

Please report a new issue instead of commenting on PRs

2024-04-10 22:11 UTC, ansarierfan99 commented
How to do it in mobile device?

2024-04-11 04:33 UTC, thunder-coding commented
If you have any questions on how to use this package you can always create a new GitHub discussion instead of digging on old PRs: https://github.com/termux/termux-packages/discussions

Locking the PR since this is just attracting spam now