Add package: gn
termux/termux-packages pull request #7290
Opened 2021-08-09 02:25 UTC by thunder-coding

TODOs:
- [ ] Add gn
- [ ] Test if it works
- [ ] Add gn-vim
- [ ] Add gn-emacs
- [ ] Create a `termux_setup_gn` script
- [ ] Add a package that requires gn to build to test `termux_setup_gn`

2021-08-09 08:28 UTC, SPECIFIC10 commented
I need some tool to hack phone number

2021-08-09 08:36 UTC, thunder-coding commented
Its picking up the correct linker
```
cxx = aarch64-linux-android-clang++
ar = aarch64-linux-android-ar
ld = aarch64-linux-android-clang++
```
Notice `-clang++` at the end instead of `-ld`

2021-08-09 08:43 UTC, SPECIFIC10 commented
I need some tool for number hacking plz


On Mon, Aug 9, 2021, 2:06 PM YAKSH BARIYA ***@***.***> wrote:

> Its not picking up the correct linker
>
> cxx = aarch64-linux-android-clang++
> ar = aarch64-linux-android-ar
> ld = aarch64-linux-android-clang++
>
> Notice -clang++ at the end instead of -ld
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/termux/termux-packages/pull/7290#issuecomment-895046301>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVELZTHRFIK5PQE2LTGGRA3T36HRFANCNFSM5BZD67EQ>
> .
>

2021-08-10 11:56 UTC, thunder-coding commented
The compiled `gn` works well and for testing `termux_setup_gn` script, I will be adding the v8 package and make nodejs link to that v8. The v8 version will be kept roughly near to nodejs' in order to reduce number of patches.

Also while building Node.js 16, v8 seems  to compile for wrong arch, so having shared v8 makes sense. See suhan-paradkar/termux-packages#8

2021-08-10 20:30 UTC, xeffyr requested changes
Please make sure you have checked how `termux_setup_golang` or `termux_setup_cmake` work and adjust `termux_setup_gn` accordingly.

Specifically:
* Need integrity check of downloaded tarball. No matter whether it has been downloaded and checked previously. You need to verify it always.
* Do not re-install gn if it was already installed.

2021-08-10 20:30 UTC, xeffyr commented on scripts/build/setup/termux_setup_gn.sh
> +	test ! -f $GN_TARFILE && termux_download \
`test ! -f $GN_TARFILE` is not necessary there.

`termux_download` will re-download it only if integrity check fails or file does not exist. Here you are disabling integrity checking of existing file.

2021-08-10 20:30 UTC, xeffyr commented on scripts/build/setup/termux_setup_gn.sh
> +	tar xf $GN_TARFILE -C $GN_FOLDER
You are extracting tar without checking the presence of already extracted installation.

2021-08-11 06:53 UTC, xeffyr approved these changes

2021-08-12 19:51 UTC, xeffyr commented
Fails at
```
ERROR at //BUILD.gn:5285:3: Assertion failed.
  assert(!is_component_build)
  ^-----
```

Possibly you need to add `is_component_build=false`.

2021-08-13 01:47 UTC, suhan-paradkar commented
It requires libicu now??

2021-08-13 02:40 UTC, thunder-coding commented
> It requires libicu now?? 

It requires icu for i18n support

2021-08-13 06:39 UTC, hnmn commented
ig `target_os="android"` be correct 
Also `target_os = ['android'] ` need in .gclient

2021-08-13 14:40 UTC, thunder-coding commented
I got it why v8 fails with shared v8, libicu is missing pkg configs, I will push the fix soon.

And I got v8 building for x86_64, aarch64 build is going on.

If it passes, I will add patches for v8 which will be stealed from nodejs vi patches

2021-08-14 02:15 UTC, suhan-paradkar commented
Well.. 32 bit CPUs are facing few strange problems with gn..

2021-08-14 09:18 UTC, thunder-coding commented
> Well.. 32 bit CPUs are facing few strange problems with gn..

Probably that's due to some variables defined in `scripts/build/termux_step_setup_toolchain.sh`

Will try unsetting all if them after CI for aarch64 and x86_64 pass

2021-08-14 15:16 UTC, suhan-paradkar commented
Well... About aarch64 build... Looks like the CI ran out of space... ![Screenshot_2021-08-14-20-45-55-29.jpg](https://user-images.githubusercontent.com/76830230/129450940-3667cb1f-8fa9-4bb0-99e4-e36541140b77.jpg)

2021-08-14 15:21 UTC, suhan-paradkar commented
Same about x86_64 too

2021-08-14 16:57 UTC, thunder-coding commented
Now, that I have revised libicu to include pkg-config, I can confirm that V8 is looking for icu-i18n.pc at a really wrong place

https://github.com/chromium/chromium/blob/be8ee8535827682b07c0864c165eb9bca4005521/build/config/sysroot.gni#L20

2021-08-17 13:38 UTC, thunder-coding commented
https://github.com/chromium/chromium/blob/master/docs/clang.md

Seems like V8 uses a different clang binary than what we expect to compile stuff with.

2021-08-17 15:59 UTC, xeffyr commented
@thunder-coding The problem is `--sysroot=../../../../../../../data/data/com.termux/files`. Termux prefix is not valid compiler system root. There should be something like `--sysroot=$TERMUX_STANDALONE_TOOLCHAIN/sysroot` instead. Any headers and library paths of dependencies should be included through CFLAGS and LDFLAGS respectively.

2021-08-18 07:10 UTC, thunder-coding commented
The input errors seem to be prominent even after setting sysroot to `$TERMUX_STANDALONE_TOOLCHAIN/sysroot`

2021-08-20 10:37 UTC, hnmn commented
`v8_enable_i18n_support=false`  try this

2021-08-20 10:38 UTC, thunder-coding commented
> `v8_enable_i18n_support=false`  try this 

This works, but at the cost of i18n support which is not desired.

2021-08-21 07:49 UTC, hnmn commented
Can we just follow the official build guide for cross compiling v8?
Ig gn is looking for ndk at $v8_root/third_party

2021-08-29 08:16 UTC, thunder-coding commented
V8 seems to have a lot of problems compiling for Termux. Should I skip adding it? Atleast we can have GN for those who would like to have it...

2021-09-01 09:04 UTC, thunder-coding commented
Okay, so I have removed all my commits for V8. I might try if I can get it building in another PR. And about the `termux_setup_gn` script, I am sure it will work, but for evey package that requires GN to build, we may need to patch respective `BUILD.gn` file of the same in order to make it choose correct build tools because GN doesn't by itself choose proper build tools from environment variables.

2021-09-03 17:45 UTC, xeffyr approved these changes

2021-09-03 17:46 UTC, merged