Add package groff
termux/termux-packages pull request #7617
Opened 2021-09-29 11:25 UTC by Maxython

#2056

2021-09-29 12:37 UTC, Maxython commented
The libxaw package is needed to compile, but it is in termux-x11.

2021-09-29 13:00 UTC, Maxython commented
Porting to termux-x11

2021-09-29 13:52 UTC, Maxython commented
https://github.com/termux/x11-packages/pull/443

2021-09-29 13:57 UTC, xeffyr commented
From what time `groff` became the X11 package?

2021-09-29 14:00 UTC, xeffyr commented
Don't look at https://archlinux.org/packages/core/x86_64/groff/. Termux goes its own way, neither Debian-specific nor Arch, for all package types.

2021-09-29 14:17 UTC, Maxython commented
> From what time `groff` became the X11 package?

Yes, it looks strange. I did this to make `groff` compile with `libxaw`, it just doesn't see this library from this repo.

2021-09-29 14:28 UTC, xeffyr requested changes

2021-09-29 14:28 UTC, xeffyr commented on packages/groff/build.sh
> +TERMUX_PKG_BUILD_DEPENDS="netpbm, psutils, libice, libsm, libxau, libxdmcp, libxcb"
Remove netpbm, psutils and x11 packages from there. `gxditview` is not a critical functionality also switching to `man-db` from `mandoc` is not planned currently.

2021-09-30 10:45 UTC, xeffyr commented
Try `TERMUX_PKG_BUILD_IN_SRC=true`

2021-09-30 11:14 UTC, Maxython commented
Thank

2021-09-30 14:03 UTC, Maxython commented
Well, despite the fact that it compiled, it did not pass the test.  I also made a compilation for myself, the result: some commands do not work, but they are united by one conclusion.  
```
FORTIFY: %n not allowed on Android                           
Aborted
```
Now guess what it is, it's either the code or the compiler.

2021-09-30 14:20 UTC, xeffyr commented
@Maxython Look existing patches. That's due to old gnulib which doesn't have fix for Android 10.

Sample patch made for `m4`, now removed after upstream update:
```.diff
diff --git a/packages/m4/lib-vasnprintf.c.patch b/packages/m4/lib-vasnprintf.c.patch
new file mode 100644
index 000000000..095184b5b
--- /dev/null
+++ b/packages/m4/lib-vasnprintf.c.patch
@@ -0,0 +1,12 @@
+diff -u -r ../m4-1.4.18/lib/vasnprintf.c ./lib/vasnprintf.c
+--- ../m4-1.4.18/lib/vasnprintf.c	2016-12-31 13:54:42.000000000 +0000
++++ ./lib/vasnprintf.c	2019-10-02 19:32:13.576211922 +0000
+@@ -4858,7 +4858,7 @@
+ #endif
+                   *fbp = dp->conversion;
+ #if USE_SNPRINTF
+-# if !(((__GLIBC__ > 2 || (__GLIBC__ == 2 && __GLIBC_MINOR__ >= 3)) && !defined __UCLIBC__) || ((defined _WIN32 || defined __WIN32__) && ! defined __CYGWIN__))
++# if !(((__GLIBC__ > 2 || (__GLIBC__ == 2 && __GLIBC_MINOR__ >= 3)) && !defined __UCLIBC__) || ((defined _WIN32 || defined __WIN32__) && ! defined __CYGWIN__) || defined(__ANDROID__))
+                 fbp[1] = '%';
+                 fbp[2] = 'n';
+                 fbp[3] = '\0';
```

2021-10-01 09:52 UTC, xeffyr commented
You are attempting to run cross-compiled binary. This is not possible as our build environment is strictly Ubuntu x86_64.
```
  GROFF    doc/meintro.ps
/bin/bash: line 1: /home/builder/.termux-build/groff/src/groff: cannot execute binary file: Exec format error
```

You need to perform a host build (relevant examples are available in ./packages/*) and add path to host-compatible `groff` to PATH. You may need to patch build system to avoid picking cross-compiled groff.

2021-10-01 18:28 UTC, Maxython commented
I tried installing and noticed the first problem, a conflict with the `man` package because of the `soelim` command.
![Screenshot_20211001-212545_Termux](https://user-images.githubusercontent.com/60917834/135669432-54b47102-3b3c-4007-8b72-d9a758536443.jpg)

2021-10-01 19:41 UTC, Maxython commented
> You need to perform a host build (relevant examples are available in ./packages/*) and add path to host-compatible groff to PATH.

I just turned off these tests, but your version sounds more correct.

2021-10-02 11:41 UTC, merged

2021-10-02 11:56 UTC, Maxython commented
@xeffyr, such a situation with `groff` and c `man` is so to itself.  I've already set it up so that `groff` doesn't conflict with `man`.

2021-10-02 15:34 UTC, Maxython commented
https://github.com/termux/termux-packages/pull/7630