New package: marisa
termux/termux-packages pull request #8050
Opened 2021-11-24 12:10 UTC by ifurther

#7883

2021-11-26 07:59 UTC, Grimler91 requested changes

2021-11-26 19:28 UTC, ifurther commented on packages/marisa/build.sh
> +TERMUX_PKG_LICENSE="custom"
OK, I updated it.

2021-11-26 19:53 UTC, Grimler91 commented
Rebasing against master will fix the build error it fails with now

2021-11-27 23:19 UTC, Grimler91 commented
Thanks, merged: https://github.com/termux/termux-packages/commit/f6e47e1b4f7e447321ac44b7d7b6f12d31a3f1ff

2021-11-27 23:19 UTC, closed without merging