new package: apktool
termux/termux-packages pull request #8212
Opened 2021-12-12 06:09 UTC by xtkoba

Closes #1286.

2021-12-12 14:04 UTC, xeffyr requested changes
`apktool` includes `aapt` binary into jar file. By default it is not compatible with Termux/Android.

2021-12-16 00:09 UTC, xtkoba commented
Bundled `aapt` is now replaced with wrapper executing `$PREFIX/bin/aapt`.

2021-12-16 19:12 UTC, xeffyr approved these changes

2021-12-16 19:13 UTC, merged

2021-12-16 19:14 UTC, xeffyr commented
We don't have `aapt2` package. If `apktool` won't fallback to use of `aapt`, issues are expected.