Update some packages
termux/termux-packages pull request #8217
Opened 2021-12-12 15:22 UTC by Yisus7u7

2021-12-12 15:27 UTC, Yisus7u7 commented
@xeffyr 
After this update, many packages in x11-packages will have to be rebuilt, since most use the services of dbus.

2021-12-12 15:47 UTC, Grimler91 commented
Please try to use more informative commit messages:

`Update some packages` does not say what packages are involved, and gives the impression that multiple packages are being updated (rather than just dbus). `dbus: update to 1.13.18` is a better description of what the commit does.

`Fix script` gives the impression that you are fixing a script in the scripts/ directory rather than the build.sh recipe for dbus. This commit should/could in any case be squashed with the first one.

2021-12-12 15:48 UTC, Grimler91 requested changes

2021-12-12 15:48 UTC, Grimler91 commented on packages/dbus/build.sh
> +TERMUX_PKG_REVISION=4
No need to bump revision. The line can be removed when increasing TERMUX_PKG_VERSION

2021-12-12 15:51 UTC, Yisus7u7 commented
Done

2021-12-12 15:54 UTC, Grimler91 commented
The TERMUX_PKG_REVISION line can be removed, and I would prefer if you squash the commits into one, see for example https://stackoverflow.com/a/50443893 on how to do that

2021-12-12 16:06 UTC, Yisus7u7 commented
> The TERMUX_PKG_REVISION line can be removed, and I would prefer if you squash the commits into one, see for example https://stackoverflow.com/a/50443893 on how to do that

xeffyr had explained to me that every time a package is modified, TERMUX_PKG_REVISION had to be increased, no matter what modification it was.

2021-12-12 16:08 UTC, Yisus7u7 commented
> The TERMUX_PKG_REVISION line can be removed, and I would prefer if you squash the commits into one, see for example https://stackoverflow.com/a/50443893 on how to do that

This is not the "master" branch, therefore if the change works it will only be a confirmation and not all the ones I did.

2021-12-12 16:18 UTC, Grimler91 commented
> > The TERMUX_PKG_REVISION line can be removed, and I would prefer if you squash the commits into one, see for example https://stackoverflow.com/a/50443893 on how to do that
> 
> xeffyr had explained to me that every time a package is modified, TERMUX_PKG_REVISION had to be increased, no matter what modification it was.

Only if TERMUX_PKG_VERSION is not changed

> > The TERMUX_PKG_REVISION line can be removed, and I would prefer if you squash the commits into one, see for example https://stackoverflow.com/a/50443893 on how to do that
> 
> This is not the "master" branch, therefore if the change is merged it will only be a confirmation and not all the ones I did.

I don't understand what you are trying to say here unfortunately, what "confirmation"? It doesn't matter that your branch is not master, you can do 
```
git clone https://github.com/Yisus7u7/termux-packages -b patch-1
### Or, if you have uploaded an ssh pubkey to github:
# git clone git@github.com:Yisus7u7/termux-packages -b patch-1
cd termux-packages
git rebase -i HEAD~3
```
And follow instructions in linked post to squash the three commits into one. You can then force push to your branch to update this PR:
```
git push -f https://github.com/Yisus7u7/termux-packages patch-1
### Or:
# git push -f git@github.com:Yisus7u7/termux-packages patch-1

2021-12-20 14:08 UTC, xeffyr approved these changes

2021-12-20 14:08 UTC, merged

2021-12-20 14:11 UTC, Yisus7u7 commented
@xeffyr
You can update the submodule in x11-packages?, do you have to update now many packages that depend on dbus