add package pipes.sh
termux/termux-packages pull request #8278
Opened 2021-12-18 23:41 UTC by Efreak

A pipes screensaver for console.

![Screenshot_20211218-154117_Termux](https://user-images.githubusercontent.com/749751/146658377-a73a706f-3533-4438-a759-3828de3dfbce.png)

2021-12-19 08:03 UTC, xeffyr requested changes

2021-12-19 08:03 UTC, xeffyr commented on packages/pipes.sh/build.sh
> +TERMUX_PKG_VERSION=1.3.0+ #if there's ever a new release, switch to it
Remove "+".

If you prefer git version or package doesn't provide tags, use commit date here or date when you have added/upgraded package.

2021-12-19 08:03 UTC, xeffyr commented on packages/pipes.sh/build.sh
> +TERMUX_PKG_SRCURL=https://github.com/pipeseroni/pipes.sh/archive/refs/heads/master.zip # in the meantime, master has a bunch of changes
Source code downloads must be deterministic. Please use tags (if possible) or specific commit. `master.zip` will change over time and will make git history for that package useless.

2021-12-19 09:50 UTC, merged

2021-12-19 10:04 UTC, Efreak commented
Somehow, this isn't making a .deb file still.

2021-12-20 15:12 UTC, buttaface commented
Maybe [it has a problem with the `.` in the package name](https://github.com/termux/termux-packages/runs/4573808528?check_suite_focus=true#step:3:122)?

2021-12-20 15:17 UTC, xeffyr commented
@buttaface Debian packages allow `.` (dot) in package name.

2021-12-20 15:22 UTC, buttaface commented
Could be a problem on our CI first, see the error I linked.

2021-12-20 15:24 UTC, xeffyr commented
I've pushed fix for regexp in github actions config.