new package: enblend
termux/termux-packages pull request #8354
Opened 2021-12-26 08:40 UTC by xtkoba

Closes #1157.

2021-12-26 15:25 UTC, xeffyr requested changes

2021-12-26 15:25 UTC, xeffyr commented on packages/enblend/build.sh
> +TERMUX_PKG_VERSION=4.2.0_p20161007
`_` is not allowed in version field.

2021-12-26 15:32 UTC, kornbik reviewed
#8354

2021-12-26 15:47 UTC, xtkoba commented on packages/enblend/build.sh
> +TERMUX_PKG_VERSION=4.2.0_p20161007
Fixed. Thanks!

2021-12-27 04:46 UTC, kornbik reviewed
#8354

2021-12-28 15:13 UTC, xeffyr approved these changes

2021-12-28 15:14 UTC, merged