Apt:Upgrade to 2.3.15
termux/termux-packages pull request #8891
Opened 2022-02-03 12:09 UTC by NoNameMan1231

2022-02-03 12:16 UTC, NoNameMan1231 commented
OPPS look like I missed something

2022-02-03 12:26 UTC, thunder-coding requested changes

2022-02-03 12:26 UTC, thunder-coding commented on packages/apt/build.sh
>  TERMUX_PKG_SHA256=b90a3ced152ecd389a55da1115e04565bfcbf5f58a808cdb71f6b52d4d2f0bdf
Also update the checksum

2022-02-04 04:59 UTC, NoNameMan1231 commented on packages/apt/build.sh
>  TERMUX_PKG_SHA256=b90a3ced152ecd389a55da1115e04565bfcbf5f58a808cdb71f6b52d4d2f0bdf
Fixed

2022-02-04 05:31 UTC, merged