new package zsh-completions
termux/termux-packages pull request #9713
Opened 2022-03-31 10:53 UTC by Freed-Wu

2022-03-31 12:08 UTC, Grimler91 commented
Have you checked so that none of the existing zsh completions conflict with this one? 

Please add `TERMUX_PKG_RECOMMENDS=zsh-completions` to zsh also

2022-03-31 12:21 UTC, Freed-Wu commented
Do you mean change `TERMUX_PKG_DEPENDS=zsh` to `TERMUX_PKG_RECOMMENDS=zsh`?
However, bash-completion uses `TERMUX_PKG_DEPENDS=bash`. Is there any difference?

2022-03-31 12:41 UTC, Freed-Wu commented
Oh, I get, you means change zsh.

2022-03-31 12:46 UTC, Grimler91 commented
> Oh, I get, you means change zsh.

Yes, since zsh-completions enhance zsh it would be nice to have it recommend or suggest zsh-completions

2022-03-31 12:48 UTC, Freed-Wu commented
zsh-completions will not conflict with the existed zsh completions because they
don't accept these completions existed in other programs.

2022-04-01 10:21 UTC, xtkoba requested changes
`TERMUX_PKG_RECOMMENDS` affects package metadata. Please bump `TERMUX_PKG_REVISION` (for `bash` and `zsh`).

2022-04-01 10:21 UTC, xtkoba commented on packages/zsh-completions/build.sh
> +TERMUX_PKG_LICENSE=BSD
The license is Zsh license, not `BSD`. Specify `custom` for `TERMUX_PKG_LICENSE`.

2022-04-01 11:44 UTC, Freed-Wu commented
OK.

2022-04-01 11:50 UTC, xtkoba requested changes

2022-04-01 11:50 UTC, xtkoba commented on packages/bash/build.sh
> +TERMUX_PKG_REVERSION=2
Should be `TERMUX_PKG_REVISION=1`

2022-04-01 11:50 UTC, xtkoba commented on packages/zsh/build.sh
> +TERMUX_PKG_REVERSION=2
Should be `TERMUX_PKG_REVISION=1`

2022-04-01 11:54 UTC, xtkoba requested changes

2022-04-01 11:54 UTC, xtkoba commented on packages/zsh-completions/build.sh
> +TERMUX_PKG_LICENSE=custom
Needs `TERMUX_PKG_LICENSE_FILE`:

```bash
TERMUX_PKG_LICENSE_FILE="LICENSE"
```

2022-04-01 12:42 UTC, Freed-Wu commented
OK.

2022-04-01 19:28 UTC, xtkoba requested changes
Not `TERMUX_PKG_REVERSION` but `TERMUX_PKG_REVISION`.

2022-04-02 01:44 UTC, Freed-Wu commented
ok.

2022-04-02 03:15 UTC, xtkoba approved these changes

2022-04-02 08:06 UTC, merged