add TERMUX_PLATFORM_INDEPENDENT for pipes.sh
termux/termux-packages pull request #9897
Opened 2022-04-06 14:58 UTC by Freed-Wu

2022-04-06 15:12 UTC, thunder-coding requested changes

2022-04-06 15:12 UTC, thunder-coding commented on packages/pipes.sh/build.sh
> +TERMUX_PKG_PLATFORM_INDEPENDENT=bash
```suggestion
TERMUX_PKG_PLATFORM_INDEPENDENT=truw
```

2022-04-07 01:04 UTC, Freed-Wu commented
fix typo

2022-04-07 06:12 UTC, thunder-coding approved these changes

2022-04-07 06:14 UTC, merged